### ISSUE TITLE
[Question]: Use `DT` instead of `shiny` for data table output?

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#103]
### What is your question?

In the Getting Started vignette [example application](
https://github.com/insightsengineering/teal.slice/blob/b3b319ca4a7bde017414b03d9d76d7ab47c2141e/vignettes/teal-slice.Rmd#L50) we use `shiny::dataTableOutput/renderDataTable`. However, these are marked superseded and Shiny recommends using the `DT` package. Using the `shiny` functions can cause issues if using Bootstrap 4 (see below).

We made a note of this in the vignette so users will be aware. But, do we want to use the `DT` functions instead of `shiny`? If so, this would need `DT` to be added to the 'Suggests' field in the description.

Using Bootstrap 4 (add `theme = bslib::bs_theme(version = 4)` to `fluidPage` in example app):

![image](https://user-images.githubusercontent.com/36482959/192580526-444c2646-457f-42c7-bc94-3c69a219586e.png)

![image](https://user-images.githubusercontent.com/36482959/192580857-0ae1a511-b2da-4430-884c-a48ee5a78a23.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
The update mentioned in the vignette is sufficient, especially since it only applies to the example code in the vignette.
Let's keep as is for now.
