### ISSUE TITLE
[Bug]: Wrongly placed reset buttons in DateFilterState

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#111]
### What happened?

Regardless the app. I suggest to look at the DatetimeFilterState and arrange UI elements similarly.  

Compare https://github.com/insightsengineering/teal.slice/blob/06be449e2738811f83e6e51cfc167b18d5e3a90d/R/FilterState.R#L2169
with https://github.com/insightsengineering/teal.slice/blob/06be449e2738811f83e6e51cfc167b18d5e3a90d/R/FilterState.R#L2486

![image](https://user-images.githubusercontent.com/6959016/195033997-ec358d39-30e1-4b8a-955b-d490ac899095.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by mhallal1** [comment]
@Polkas this was fixed no?

**Comment by Polkas** [comment]
I will check that.

**Comment by Polkas** [comment]
Great finding I skiped it by mistake. I will create a PR.
