### ISSUE TITLE
[Feature Request]: FilterState to not show shiny inputs by default

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#129]
part of #48 
### Feature description

Please see the [wireframe](https://drive.google.com/file/d/1jYjYZR6Yqtfv7ZzMfBMa2T5xYIwWmVL7/view?usp=sharing)

1. Shiny inputs should not be visible by default. So called filter-card-summary (ui of the FilterState) should displayed - showing summarized information of the filer-state.
2. User clicks the active button in filter-card-summary to trigger change from filter-card-summary to filter-card-interactive. (Button can be a small gear icon or the card itself).
3. filter-card-interactive is rendered each time it's triggered to show (selection is based on the current state). User can change the values in filter-card-interactive and they are not propagated immediately until one clicks save. Once saved card turns back again to filter-card-summary with a new values. Thanks to updating values of the interactive selection after save only, we don't need a set_selected_reactive anymore (please see below).

--------

Important: Please be aware of how the FilterState$private$selected can be changed. Please see `help(teal.slice:::FilterState)` and go to the modyfying state, you'll see following image:

![image](https://user-images.githubusercontent.com/6959016/203494551-e63169f5-d51d-4aeb-a07d-10bcda41df27.png)

Filter states can be changed in three ways. See example [FilterState$server](https://github.com/insightsengineering/teal.slice/blob/e866d4dd6f7d3d3cec23725b1df8adabc8e506b6/R/FilterState.R#L1140):
- In the interactive session by directly specifying values of selected, keep_na or keep_inf using set_state method (to update all at once), or using set_selected, set_keep_na or set_keep_inf
- In a teal application by changing appropriate inputs
- Using methods set_selected_reactive, set_keep_na_reactive, set_keep_inf_reactive which serves as a programmatic API.

Important improvement would be to remove area in the dashed rectangle which will simplify [this](https://github.com/insightsengineering/teal.slice/blob/e866d4dd6f7d3d3cec23725b1df8adabc8e506b6/R/utils.R#L196) process.

**Comment by nikolas-burkoff** [comment]
If this issue involves adding a "save" button to apply the filters then: #133 and #158 should also be done with this
