### ISSUE TITLE
Move the add new filter next to the list of filters

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#13]
Related to https://github.com/insightsengineering/teal/issues/285

![image](https://user-images.githubusercontent.com/15201933/157265601-47fe173e-c122-4b56-b55f-20b4e0128700.png)

Also be aware of MAE filtering as well

**Comment by gogonzo** [comment]
Closing as the new version of the filter panel will include necessary changes:

https://github.com/insightsengineering/teal.slice/issues/47
