### ISSUE TITLE
[Feature Request]: Implement label to the filter-state

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#130]
part of #48 should rather follow https://github.com/insightsengineering/teal.slice/issues/129
### Feature description

Label should be a reactiveValue which: 
1. by default it observes private$selected (filter values) and label should be:
    - for numeric, dates and datetime `{dataname}.{varname}: {min(selected)}-{max(selected)}` 
    - for characters and factors `{dataname}{varname}: {paste(selected, collapse = ",")}`. Length of the label should be limited to X characters. We can figure value of X during the implementation
1. It should observe also textInput where user can specify the label. After label is applied - it no longer follows reactive selection (1)
1. Please add protection to not have a duplicated `label`.
 
![image](https://user-images.githubusercontent.com/6959016/203496660-c57cd2ab-6cec-45c0-9fe6-3f571caf048a.png)

**Comment by donyunardi** [comment]
I think this was done with:

**Comment by gogonzo** [comment]
I think this is still needed but the result should be discussed. Maybe users should be allowed to set values of the filter, name it accordingly (e.g. "adult") to avoid showing numbers which might not say anything. I'd like to discuss this at some point

**Comment by donyunardi** [comment]
Thanks, we can discuss this more. 
Priority-wise, let's address this at the next increment.

**Comment by donyunardi** [comment]
Let's start the discussion.

@lcd2yyz 
Could you please define the expectation of the filter-state label from user's perspective? 
* How the label should look based on current design?
* What's the behavior of the label?
* Should value be shown under the label or should it tooltips, etc?
* I think filter-state label is motivated by citril/citril.metadata, should we gather user requirement from that team too?

**Comment by lcd2yyz** [comment]
This is closely related to #220 , let's tackle these together in a discussion session.

**Comment by donyunardi** [comment]
Per discussion with @lcd2yyz, this is no longer needed in favor of filter expression.
