### ISSUE TITLE
Enable multiple filter_panel module calls

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#135]
Why?

We are moving towards module-specific-filter-panel which means that controlling module filters through single UI element is either impossible or too complicated to address.

First obstacle is that we have a single filter panel UI and we are inserting new filters (see observer in [FilterStates$srv_active](https://github.com/insightsengineering/teal.slice/blob/17a8fc65deb4c8cfe948948a6e993b1af2ef496d/R/FilterStatesDF.R#L224)). If you look at this line in [FilterStates$insert_filter_state_ui](https://github.com/insightsengineering/teal.slice/blob/17a8fc65deb4c8cfe948948a6e993b1af2ef496d/R/FilterStates.R#L380) you will understand that location of the HTML element where we insert new card is fixed in the class (so we have a single filter ui module for all teal_modules)

- It should be possible to call filter-panel module multiple times
- `FilteredData` should be still a single-global object
- `private$cards_container_id` should be removed

**Comment by donyunardi** [comment]
Acceptance Criteria:
* When the module changes, the filter panel should show filters related to the module.
* This will be in teal.slice for now and available for programmer to activate if they want.
* Teal still only call the filter panel once.

**Comment by gogonzo** [comment]
closed by #300
