### ISSUE TITLE
[Feature Request]: Implement fixed filter feature

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#141]
blocked by #187 

### Feature description

We need to modify FIlterState class to have a `fixed` feature (set via api) which makes this filter non-interactive.
When `FIlterState` has property `fixed = TRUE` then it doesn't display interactive inputs but only the fixed state.

1. Property can be set via `filter_var(..., fixed = TRUE)`
2. `get_call` always return the same call
2. `ui` of such `FilterState` should display only `varname`, `label`, `dataname` and a resulting condition. 

Note: label of the fixed filter isn't the same as varlabel - it is a specific name describing the condition. For example if condition is `SEX == "F"` then label assigned would be `"Females"`. Discuss with @donyunardi and @lcd2yyz how labels describing filters should be displayed. In the current design this `label` probably should be replace what's printed in the summary.

Note: when for conditions refering to multiple we will use FilterGroup which hasn't been implemented yet.

**Comment by donyunardi** [comment]
Blocked by insightsengineering/teal.slice#140

**Comment by gogonzo** [comment]
class should be initialized with following arguments:

- id
- dataname
- label
- condition

Class should inherit from the `FIlterState`. Because class won't have any inputs, everything will be fixed. You will notice which methods from the `InteractiveFilterState` can be moved to filter state - I think `ui` and `server` can be abstract for both `Interactive*` and `Fixed*`.
- `ui_inputs` will list `dataname`, `condition` and `label`
- `srv_inputs` will return NULL
- `ui_summary` will list current condition and dataname.

**Comment by lcd2yyz** [comment]
> @lcd2yyz If InteractiveFilterState looks like this, how FixedFilterState should look like (filter label like citril label). Of course they should display `$id $label` on the header instead of `$varname $label`, but should we include anything else (we still have a condition and dataname information)

Following your screencap, this is what I'm thinking...
- On collapse, just the `$id $label` as you mentioned. No need to show the selected values as it cannot be changed regardless
- On expansion (if clicked on), display the full filter condition.
I like the padlock icon idea to differentiate between interactive vs fixed, and I assume the enable/disable toggle will also be present.
![image](https://user-images.githubusercontent.com/78242757/222512598-9b19ac68-9eaa-461d-87d8-6e209257443b.png)

**Comment by gogonzo** [comment]
After discussion with @chlebowa @BLAZEWIM we also considering alternative solution to implement fixed into current `FIlterState` classes. How would this work:

1. One can specify filter in the same way as normal flter, by using `filter_var(selected = ..., fixed = TRUE)`
2. If using metadata from citril, then one can use special wrapper which would instantly convert citril condition into `selected`, `varname` etc. If citril condition contains multiple variables in the condition then it would return multiple `filter_var` for each variable used in the condition.
3. `FilterState` with flag `fixed` would still keep features of normal `FilterState` (validation of the choices, range etc.) but we will have to present different `ui` and `server` for them

**Comment by donyunardi** [comment]
Thanks for discussing this.
One question, if we no longer need to create `FixedFilter` class, do we still need the `InteractiveFilter` class?

**Comment by chlebowa** [comment]
We do not. The change has been been reverted on the filter API branch.

**Comment by gogonzo** [comment]
I've updated description in the initial comment

**Comment by chlebowa** [comment]
> Note: label of the fixed filter isn't the same as varlabel - it is a specific name describing the condition. For example if condition is `SEX == "F"` then label assigned would be `"Females"`. Discuss with @donyunardi and @lcd2yyz how labels describing filters should be displayed. In the current design this `label` probably should be replace what's printed in the summary.

Applying a different label will be troublesome without adding a new argument for this purpose.

**Comment by chlebowa** [comment]
Implemented in #257
