### ISSUE TITLE
[Feature request]: Counts of the levels should include filtered/unfiltered information: FilterState with slider

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#142]
blocked by #131 

1. FilterState with slider should have a density which shows how much data has been filtered. The bars should show unfiltered data and what remained after filtering (5)
![image](https://user-images.githubusercontent.com/6959016/207281335-32947789-1e32-4e69-a3fd-ac24f343a2c0.png)
2. ~~FilterState with checkbox should show bars for filtered and unfiltered counts.~~
     - ~~F (100/231)~~
     - ~~M (50/169)~~
3. ~~FilterState with pickerInput - labels of the pickerInput should show similar counts to the (2). See the RACE filter for example~~

**Comment by donyunardi** [comment]
Create new issues for item 2 and 3:
insightsengineering/teal.slice#161
insightsengineering/teal.slice#162
