### ISSUE TITLE
[Feature Request]: Change ui/srv_add_filter_state to include FilterGroups

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#143]
### Feature description

We still need a decision where to locate this module (should it stay in the same place or shown when `+` is clicked or in the filter-manager).

![image](https://user-images.githubusercontent.com/6959016/207302530-fb5eb4f7-88dd-488f-9bfc-d80c13e9938b.png)

Except a possible location change we need to enable option to add a filter-group. 
- this pickerInput should allow selecting multiple values. After selecting value(s) `srv_add_filter_state` should decide if it's a `InteractiveFilterState`, `FixedFilterState` or `FilterGroup` (more than 1 selected). The new objects should be added to the `ReactiveQueue`.
- The dropdown list should contain existing FilterStates and filter-columns. All these object can be combined within a group
- It the new group contains existing FilterState then this FilterState should be duplicated and included into the group (don't move-remove existing FilterState)

![image](https://user-images.githubusercontent.com/6959016/207299174-d2bb0feb-4374-462e-98fc-5f7cb7babe33.png)

**Comment by asbates** [comment]
Should we have a separate issue to implement a filter group with the new API? If not it would need to be a part of this issue.

**Comment by donyunardi** [comment]
At the moment, we will not be pursuing this feature.
