### ISSUE TITLE
Enable / disable filters on a variable level (but not removing it)

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.slice#15]
temporarily disable filter but not removing it

this would need a special api in filtered data - some disabled state of each of the filter

PRIORITY IS TO HAVE A BUTTON TO DISABLE (NOT REMOVE) ALL FILTERS AT ONCE (on the left of the top garbage button), then try to work on per variable scope.

![image](https://user-images.githubusercontent.com/12943682/128366489-20c9e46f-9187-4ee9-bce6-25ecb4e262cf.png)

Provenance: 
```
Creator: pawelru
```

**Comment by gogonzo** [comment]
@pawelru I guess this is might be still valid

**Comment by asbates** [comment]
@donyunardi @gogonzo Can you check my understanding of this please.

1. Right now we have a disable filter panel switch. When the switch is off (disabled) the filter states are cached and then removed. The change here is to not cache and remove all the filters but disable them.
2. We also want to be able to disable a _single_ filter state while keeping the others enabled.

**Comment by gogonzo** [comment]
> 1. Right now we have a disable filter panel switch. When the switch is off (disabled) the filter states are cached and then removed. The change here is to not cache and remove all the filters but disable them.
> 2. We also want to be able to disable a single filter state while keeping the others enabled.

(2) is what we need. Issue refers to a single card. Disable all filters (1) is implemented at this moment in the way you described and we haven't concluded if we want to change the behaviour - if you see the room for improvement please write your comment. So, please focus on (2)
