### ISSUE TITLE
`shinyjs` crashes some apps

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#157]
### What happened?

Example apps in vignettes do not contain a `shinyjs::useShinyjs()` call, but `FilteredDataset` uses `shinyjs` functions, especially after #146. However, adding `shinyjs::useShinyjs()` seems to break the apps:

without `useShinyjs`:
![image](https://user-images.githubusercontent.com/114988527/212135914-a8589e04-4aef-43e2-9503-75f69fb7631a.png)

with `useShinyjs`:
![image](https://user-images.githubusercontent.com/114988527/212135761-e50a708e-955e-4e3c-92a1-559e976bace3.png)

Notably, apps from `teal.gallery` and other example apps are not affected.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by nikolas-burkoff** [comment]
Also note the behaviour of some of the collapse buttons changes in shiny (not teal) apps which use the filter panel 
![image](https://user-images.githubusercontent.com/15201933/212150394-fe7b61da-c445-4c55-b2ac-d077ae941b3d.png)

**Comment by chlebowa** [comment]
Precisely, these minimize buttons rely on `shinyjs`, the other ones use JS to toggle their respective panels. Close buttons not affected as they alter the filter states and display effects follow from that.
