### ISSUE TITLE
Date and DateTime invalid ranges crashes app

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#158]
From https://github.com/insightsengineering/teal.slice/pull/155#pullrequestreview-1246449405

Change date or date time so that the "from" is after "to":

![image](https://user-images.githubusercontent.com/15201933/212277430-9b28e92a-94b3-4b3c-919c-bce6103996fc.png)

And the app crashes: 

![image](https://user-images.githubusercontent.com/15201933/212277549-23ea4834-bb2c-41df-9f01-7435c5400933.png)

![image](https://user-images.githubusercontent.com/15201933/212277606-0488dc58-aa6b-40da-8cc6-be6f32206689.png)

```
library(teal)
library(scda)

adsl <- synthetic_cdisc_dataset("latest", "adsl")

app <- init(
  data = teal_data(dataset("ADSL", adsl)),
  modules = example_module()
)

runApp(app)

```

This should be fixed alongside #133 when there is a "save" button to enable validation of filter panel inputs.

Please also add tests

**Comment by nikolas-burkoff** [comment]
See https://github.com/insightsengineering/teal.slice/issues/133#issuecomment-1403708823 for example shinyvalidate with these  widgets

**Comment by donyunardi** [comment]
Should we consider changing this to dateRangeInput?
Here's an example where it's impossible for user to pick an end date less than start date.
This way, we probably don't need to create any validation.

This could be along the line when @asbates mentioned about observeEvent today.

```r
library(shiny)
ui <- fluidPage(
  dateRangeInput("date_range", "Input date range", start = "2001-01-01", end = "2001-02-01")
)

server <- function(input, output, session) {
    observeEvent(input$date_range[1], {
        end_date = input$date_range[2]
        if (input$date_range[2] < input$date_range[1]) {
            end_date = input$date_range[1]
        }        
        updateDateRangeInput(session, "date_range",
        label = "Date range",
        start = input$date_range[1],
        end = end_date,
        min = input$date_range[1]
        )
    })
}

shinyApp(ui, server)
```

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* Create a flow to prevent user to pick a start date < end date
