### ISSUE TITLE
timezone issue with airDatepickerInput

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#159]
From https://github.com/insightsengineering/teal.slice/pull/155#pullrequestreview-1246169971

On some systems:

```
library(teal)

DF <- data.frame(datetime = Sys.time() + 1:100)

default_filters <- list(
  DF = list(
    datetime = list()
  )
)

app <- init(
  data = teal_data(
    dataset("DF", DF)
  ),
  modules = example_module(),
  filter = default_filters
)

runApp(app)
```

Crashes the app
![image](https://user-images.githubusercontent.com/15201933/212283371-5e4aa618-ed32-4c60-aebd-4ffdf58d09bd.png)

Because there is a timezone mismatch between the values in the airpickerinput and the values in DatetimeFilterState

Putting a breakpoint at the start of `private$observers$selection` in `DatetimeFilterState`

![image](https://user-images.githubusercontent.com/15201933/212284067-318ac136-fff7-4ebe-9bf1-e0df10a12055.png)

and as the range is so narrow end_date > private$choices[2] which means end_date is set to private$choices[2] and then we get this error

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* Investigate how the timezone behave in airDatepickerInput

**Comment by mhallal1** [comment]
For the moment, there is another error with the default empty selection in DataTime filters so the error above is not reproducible:
```
Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format
```

**Comment by mhallal1** [comment]
I could not reproduce this issue locally or on BEE. I have changed the local machine time zone to GMT and the session timezone also and the app was running perfectly. @BLAZEWIM and @chlebowa tested and had no problems.
This issue could be reproduced by @gogonzo who has the same time zone as @nikolas-burkoff. After investigating the issue on Dawid's machine, it turns out that it comes from `shinyWidgets::airDatepickerInput` which converts the data internally. There seems to be a bug in this functionality as it does not take the right even when it is assigned.

**Comment by chlebowa** [comment]
I see two problems here:

**ONE**
Nik's example app inputs a datetime created by `Sys.time()`, which contains microseconds:
```
> format(Sys.time(), "%Y-%m-%d %H:%M:%OS6", usetz = TRUE)
[1] "2023-02-27 11:39:52.829642 CET"
```
`airDatePickerInput` returns a datetime rounded to full seconds.

To solve this we can make a small change in `DatetimeFilterState$initialize`:
```
# from
var_range <- range(x, na.rm = TRUE)
# to 
var_range <- range(x, na.rm = TRUE) %>% round(units = "secs") %>% as.POSIXct()
```

However, this is only an issue in this example as normally the datetimes fed into the app will be rounded to seconds as well (or will they?).


**TWO**
`airDatePickerInput` takes the time selected, assumes it is in UTC, converts that to the local machine's time zone and returns that. This is ridiculous, but can be fixed thus:
1. accept datetime returned from input - this is UTC-assumed time converted to local time zone
2. change attribute "tzone" with `attr(dt, "tzone") <- "UTC"` - this not only changes the timezone but also adjusts the clock
3. convert to POSIXlt and run `attr(dt, "tzone") <- <correct_time_zone>` - this ONLY changes the time zone, leaving other components intact
4. convert back to POSIXct for consistency
(2-4 done by a convenience function) 

```
Browse[1]> (dt_original <- as.POSIXct("2020-02-20 12:00:00", tz = "MSK"))
[1] "2020-02-20 12:00:00 MSK"
Browse[1]> (dt <- input$selection_start)
[1] "2020-02-20 13:00:00 CET"
Browse[1]> attr(dt, "tzone") <- "UTC"
Browse[1]> (dt <- as.POSIXlt(dt))
[1] "2020-02-20 12:00:00 UTC"
Browse[1]> attr(dt, "tzone") <- attr(private$choices, "tzone")
Browse[1]> (dt <- as.POSIXct(dt))
[1] "2020-02-20 12:00:00 MSK"
```

We can also leave the date in POSIXlt after both of these changes and it will be consistent across the app.

Note: a warning is raised: `Warning in check_tzones(e1, e2) : 'tzone' attributes are inconsistent` but I cannot locate where from.

**Comment by asbates** [comment]
@gogonzo @donyunardi Have we decide what we're doing with this?

**Comment by chlebowa** [comment]
Note the crashes are gone now.
I think the consensus is: unless we know what to do right away, we leave it be until a better moment. It is tricky indeed to navigate the three time zones: the user's, the server's and that of the data as `airDatetimePicker` seems to corrupt the timezone. Possible solutions involve changing the input widget to something better or reversing the corruption like Dawid suggested.

**Comment by donyunardi** [comment]
I agree with you.
It seems like it's not very likely that we'll come across a situation where the date of the field is super close to the system date. I think we've looked into it enough for now, and we can always revisit it later if it turns out to be a bigger problem.
