### ISSUE TITLE
pickerInput labels (counts ) are too reactive

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#167]
Counts of the filter are too reactive. Selecting values instantly trigger re render of the inputs. In case of the pickerInput one is not able to select multiple values because click instantly impacts the ui-input.

https://user-images.githubusercontent.com/36482959/212970289-e8c3a460-d3cc-49e9-bbd8-78824ede4ca2.mp4

We need to find the non-invasive way to update the counts which won't retrigger reactive events. Also `pickerInput` selection should be applied only when picker is closed https://github.com/dreamRs/shinyWidgets/issues/392

**Comment by donyunardi** [comment]
Could be related with #173 and #174
Per our discussion, the accepted solution is to decouple the filter counts/label from the input so we can separate the two activities.
