### ISSUE TITLE
radioButton counts causes infinitive loop

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#173]
Please change very quickly values of the radioButton (LogicalFilterState) and see what happens. Reason for this is that by changing a selection for the second time triggers event before the first one completes. The problem lays in the `updateRadioButton` which triggers a reactive. Perhaps we need to find the other way to update the counts and "count bar" for example through `runjs` or something .

**Comment by donyunardi** [comment]
Per our discussion, the acceptance criteria is to decouple the filter counts/label from the input so we can separate the two activities.
