### ISSUE TITLE
checkboxInput counts causes infinitive loop

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#174]
Please change very quickly values of the checkboxInput and see what happens. Reason for this is that by changing a selection for the second time triggers event before the first one completes. The problem lays in the updateCheckboxInput which triggers a reactive. Perhaps we need to find the other way to update the counts and "count bar" for example through `runjs` or something .

updateCheckboxInput can be found in `ChoicesFilterState$srv_inputs`, `RangeFilterState$keep_inf_srv`, `FilterState$keep_na_srv`.

**Comment by chlebowa** [comment]
This only happens when more than one filter is active:
```
teal.gallery::launch_app("basic-teal")
```
Add filter on `iris$Species`, click away and it works fine, but add another filter on `iris` and then a doubleclick on a checkbox triggers the loop. Could it possibly be not because of `update*`?

**Comment by gogonzo** [comment]
> Add filter on iris$Species, click away and it works fine, but add another filter on iris and then a doubleclick on a checkbox triggers the loop. Could it possibly be not because of update*?

There is a possibility. That was my highest likelihood guess after analysing logs and seeing what followed what.

**Comment by chlebowa** [comment]
So @nikolas-burkoff and I tested it in an app that is a little slower than _basic-teal_ and the loop does trigger. Apparently in some cases one simply cannot click quickly enough.

**Comment by donyunardi** [comment]
Per our discussion, the acceptance criteria is to decouple the filter counts/label from the input so we can separate the two activities.
