### ISSUE TITLE
Add Helper apps into roxygen

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#179]
I think these 2 apps should be included in the roxygen documentation as they make it clearer how FilterState and FilterStates work:

- https://github.com/insightsengineering/teal.slice/pull/172#issuecomment-1406468757
- https://github.com/insightsengineering/teal.slice/pull/172#issuecomment-1406636803

**Comment by donyunardi** [comment]
Acceptance Criteria:
* Add helper document in two classes FilterState and FilterStates
* Consolidate if related example exist elsewhere in the package

**Comment by gogonzo** [comment]
I think each class (eg. `RangeFilterState`, `ChoicesFIlterState`) should have own example, simple single `fs$ui()` and `fs$server()` call, wrapped in the simple module outputing `fs$get_call` and `fs$get_selected`. We should not create app which consolidate multiple `FilterState` modules. Same regarding `FilterStates` class. One class - one example.

If examples are written for init_filter_states and init_filter_state, examples should be done for each class - the examples will get consolidated automatically as they sharing the same documentation page.

@donyunardi @nikolas-burkoff @chlebowa

**Comment by donyunardi** [comment]
Thanks @gogonzo 

I understand your perspective, and I agree that although it may require considerable effort, implementing the change that you suggested would significantly enhance the user experience with our documentation by eliminating the need for them to navigate through various files to locate examples.

If there are no objections, let's proceed with this updated acceptance criteria.
