### ISSUE TITLE
ChoiceFilterState improve init

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#183]
I think these `get_choices_label` functions are too complicated. I think we can simplify and tidy up the way how we obtain counts. In the init of `choicesFilterState` there is `private$histogram_data` which isn't used at all. Having `private$choices` where value is a factor level and name is a count is also not elegant. I think we can introduce 

```
private$choices # factor levels
private$choices_count # unfiltered count
private$f_choices_count # reactive
private$calculate_choices_count(x) 
```

That is just a proposition, I think it would be nice if we tidy up these `initialize` methods and how we preserve counts.

_Originally posted by @gogonzo in https://github.com/insightsengineering/teal.slice/issues/180#issuecomment-1411649446_

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* Simplify the property/attributes of the class
* Update the class' methods
