### ISSUE TITLE
Implement a new API

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#187]
Initial work for the #138 

Check `?filter_state_api`. There are `set_filter_state`, `get_filter_state`, `remove_filter_state` and `get_filter_state`. They are exported functions which calls methods of the same name in the `FilteredData`.
They passing the instructions to the classes  to manage FilterState in the `filter_state_list`. Currently this communication is done by passing the list, for example
```r
list(
  ADSL = list( # goes to FilteredDataset and to FilterStates
    AGE = list( # refers to FilterState for AGE column
      selected = , # initial selected values
      keep_na = , # initial value for keep_na
      keep_inf = , # initial value for keep_inf
    )
  ),
  MAE = list( # goes to MAEFilteredDataset
    subjects = list( # goes to MAEFIlterStates
       ...
    )
  )
)

```

We need to introduce a different way of passing this informations through the classes. Currently nested list shown above is transfered through `FilteredData$set_filter_state -> FilteredDataset$set_filter_state -> FilterStates$set_filter_state -> FilterState$set_state`. While passed from class to class list get unnested and `FilterState`.

We want to introduce something like this, which can be easily extended in the future by new type of filters or by new "arguments" which can cause some specific behavour of the filter-state within state_list.
```r
filters = filter_settings(

    filter_var(dataname = "ADSL", varname = "ARM", choices = c("ARM A", "ARM B", "ARM C", NA)), # list
    
    filter_var(dataname = "ADSL", varname = "AGE", label = "AGE 18-60", choices = c(18, 60)),

    mae_parient_var(dataname = "MAE", varname = "gender"),

    mae_gene_subset(dataname = "MAE", experiment_name = "e1", varname = "gene.id"),

    mae_gene_select(),

   filterable = ...

  )
```

Comparing to the current API, in the new one we should be able also to specify "choices" which will limit number of choices in the initialized filter-state.

------

Arguments of the filter_var

- @param dataname (`character(1))` name of the dataset
- @param varname (`character(1))` name of the column in dataset
- @param choices (`vector`) values of the column which should define range/set of the choices
- @param selected (`vector`) values of the choices being a default/initial selection
- @param label (`character(1)`) text describing the filter

Arguments of the filter_settings
- @param ... (`filter_var`, `mae_patient_var`, `mae_gene_subset`, `mae_gene_select`)
- @param filterable (`list`) named after datasets, containing character vectors containing columns which can be chosen to filter. Same as current implementation on main.

Because `choices` hasn't been yet implemented in the class it might be skipped if you found it difficult to just sneak-in in this PR.

**Comment by gogonzo** [comment]
Implementation should keep supporting current way of specification (using lists). Specifying a list instead of `filter_settings` should throw a warning saying `specifying filters as lists is obsolete and will be deprecated in the next release. Please see documentation of ?set_filter_state to see...`

**Comment by chlebowa** [comment]
Here is how I see this:

The _structure_ is: `FilteredData` > `FilteredDataset` > `FilterStates` > `FilterState`.

`filter_var` creates an object that I will refer to as a `teal_slice`.

A `teal_slice` is a named list that has all information necessary to set a `FilterState` from any level in the structure. These mandatory elements are: `dataname`, `varname`, `varlabel`, `choices`, `selected`, `keep_na`, `keep_inf` (optional), and `fixed`. All of these are stored in corresponding private fields in `FilterState`.

If a `FilterState` object has `private$fixed == TRUE`, none of its fields can be altered by any means. It can, however, be disabled or removed. (This links to #141). Such a `FilterState` has different (simpler) shiny UI and server functions.

A `teal_slice` can hold additional elements, that will be passed to `...` in `filter_var`. All of these is stored in one field, `private$extras` in `FilterState`. `private$extras` cannot be modified.


`filter_settings` collates multiple `teal_slice`s into a single unnamed list, `teal_slices`.
Within a `teal_slices` there is no hierarchy, each `teal_slice` is an equal element as it holds ALL information on a given `FilterState`.

Per @gogonzo's design, this allows things like `Filter(function(x) x$dataname == "dataset1", teal_slices)` to get filters pertinent to one data set. Some convenience functions can be built on this structure.

`teal_slice` and `teal_slices` are S3 classes to simplify argument checks and add some custom methods (e.g. `print`).


`FilterState$get_state` rebuilds and returns a `teal_slice` object based on current values of all appropriate fields.
`FilterStates$get_states` rebuilds and returns a `teal_slices` object based on current values of all `FilterState`s it contains.
`FilteredDataset$get_filter_states` rebuilds and returns a `teal_slices` from all `FilterStates` it contains.
`FilteredData$get_filter_states` rebuilds and returns a `teal_slices` from all `FilteredDataset`s it contains.
(some methods need renaming)


What do you think?

**Comment by chlebowa** [comment]
Once a `FilterState` has been initiated, only these fields specified by `filter_var` can be modified:
* varlabel
* selected
* keep_na
* keep_inf

**Comment by chlebowa** [comment]
The `filterable` argument in `filter_settings`: is it better to have it specify variables that can be filtered or values that can **not** be filtered? If the former, all variable names in a data set have to be typed when calling `filter_settings` as the call does not involve the data object in question. I suggest to have the argument specify "locked" variables.

**Comment by gogonzo** [comment]
> I suggest to have the argument specify "locked" variables and to have it default to character(0).

Could you elaborate more about locked? Is it alternative to "filterable"?

**Comment by chlebowa** [comment]
"locked" means non-filterable

**Comment by gogonzo** [comment]
Agree, It makes more sense because by default all columns are filterable and we only substract from this set. But I suggest attribute name containing `exclude` phrase to describe this behaviour. `locked` seems to be closer to `fixed`, don't you think?

P.S. Feel free to remove `set_filterable_varnames`

**Comment by chlebowa** [comment]
Yes, "locked" was a placeholder name. I will go with "exclude".
