### ISSUE TITLE
Hide/Remove the Subject column when processing non-cdisc data

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#201]
Can we hide the **Subjects** column when processing non-cdisc data?

<img src="https://user-images.githubusercontent.com/8597300/219518781-fb5a35dc-3e54-41cd-a488-8da59ed5d651.png" width="50%" height="50%" />

@lcd2yyz  What do you think?

**Comment by lcd2yyz** [comment]
I wouldn't say hide "Subject" column for all non-CDISC data. Rather, make it optional?
There can be many other data structure that are multiple observation per unique subject/identifier, in which case, options to 1) display and 2) pass the variable that can uniquely identify the subject would be more useful.

**Comment by gogonzo** [comment]
Duplicate https://github.com/insightsengineering/teal.slice/issues/4
