### ISSUE TITLE
When disabling filter panel, don't remove UI

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#206]
When the whole filter panel is disabled, inputs should be disabled instead of removing the entire card UI. When #15 is implemented the mechanism will exist to disable at the individual card level. So it shouldn't be difficult to adapt the current process.

@gogonzo update:
- When disabling `FIlterState` we should avoid caching and restoring. Instead `is_any_filtered` should return `FALSE` when `disabled`. We don't need caching/restoring and emptying `state` which contains `disable` information in the new API - so we can distinguish which `state` are enabled and which are disabled

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* Not delete the inputs when global panel is disabled
* Instead, with the new API, we can send signal to disable each cards
* May need to modify class

**Comment by chlebowa** [comment]
A question has come up as to what exactly is the function the global disable switch. We see two possibilities:
1) when set to `disable`, disable all filter cards, and when set to `enable`, enable all filter cards
2) when set to `disable`, disable all filter cards, and when set to `enable`, restore all filter cards to their previous state, including disabled status

@lcd2yyz, can you comment?

**Comment by lcd2yyz** [comment]
> 2\. when set to `disable`, disable all filter cards, and when set to `enable`, restore all filter cards to their previous state, including disabled status

Option 2 makes more sense.

**Comment by lcd2yyz** [comment]
> The functionality of the global and individual switches would be different in case 2 so I think it would be good to distinguish them visually.

Can you explain more about the difference that you see about the global vs individual card switch?
To me, the toggle would apply the same behavior of activate filter (enable) ->inactivate filter (disable) -> restoring previous state before disabling (re-enable). The only difference would be the level which it controls, so potentially the global switch will need to "know" many more filter states before it was inactivated.

From UX perspective, having a visual consistency of the UI component is important. So unless they are fundamentally different, I would prefer to keep the same look for the toggle switch

**Comment by asbates** [comment]
Yes I agree visual consistency is important. But I think if things are visually the same, they should have the same functionality.

The difference with the global enable/disable is that it's not enabling/disabling. For example if I have on individual card disabled, click the global disable switch, then global enable, the individual filter card is still disabled. So I clicked enable, but a filter is disabled.

On the individual filter perspective, the switch truly enables and disables. Disable means that input is disabled and the filter is not applied to the data. When enabled, the input is enabled and the filter is applied to the data.

**Comment by chlebowa** [comment]
Here's a new hurdle:
Say you flip the global disable switch and a signal is sent to all existing filter states to disable. That does not cause their individual switches to flip. So we end up with filters that are disabled but their switches are in the enabled position.

**Comment by lcd2yyz** [comment]
For global switch - "flipping" action on individual filters does not sound right to me.

Global switch will always be defaulted to be turned-on at app start. Once global switch-off, every filter (regardless active or inactive) will be un-applied and grayed out, users will not be able to change values or switch on/off individual filters anymore.
I would like to think the global switch-on action as *RESTORE* whatever the state the individual filters had prior to the global disable. These states would include active/inactive status of every filter and the last selected value of the active filters.  

If we consider switch-on action on the individual filter also to be a "restore" action - restoring whatever the state of the individual filter. At individual filter level, the state only include the last selected value.

Is this logic more convincing?
