### ISSUE TITLE
Style the filter panel

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#213]
I think there's some room for improvement for the filter panel styling. Well panel's are a bit outdated, hard coding colors (blues and red) are probably not a great idea, to start with.

We should really think about restyling across the whole app though because a lot of the same styling is used and just having the filter panel different will probably look weird.

**Comment by donyunardi** [comment]
We're now proceeding with the restyle here:
https://github.com/insightsengineering/teal/issues/1289

Closing.
