### ISSUE TITLE
Research on better solution to manually enter numeric ranges

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#234]
Continuation from #226

### Summary:
The user desires the option to manually input ranges when filtering data with a numeric variable, as well as the ability to use a slider to select ranges. The proposed solution, #226, involves implementing a toggle button that activates a numericRangeInput, which allows the user to enter a value manually while retaining the slider input. The toggle button would allow the user to switch between the slider and text box to select or enter the range.

However, there is a problem when a value is manually entered, as it must match the slider's steps or ticks. This restricts the user from freely inputting any value.

### Acceptance Criteria:
This is a research task to see if there's a better or robust solution to achieve users requirements:
* Able to use slider to select ranges
* Able to manually enter ranges

**Comment by donyunardi** [comment]
We have received feedback advising us to concentrate on the manual numeric range input, omitting the slider or tick functionality, and incorporating a distribution visualization in some form. Please bear this in mind as you conduct your research.

We do have a suggestion to use plotly:
* https://github.com/insightsengineering/teal.slice/issues/233

Please find other possible solutions.

**Comment by chlebowa** [comment]
I am working on the `plotly` thing, when it's ready I will look into @gogonzo proposed `noUiInputSlider`.

**Comment by chlebowa** [comment]
closed by #289
