### ISSUE TITLE
set/get state only through set_state/get_state

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#235]
For FilterState, I think we should only allow state to be updated and retrieved via set_state and get_state. Right now we also have for example set_selected. I think we should remove this method and only use set_state.

**Comment by chlebowa** [comment]
This was solved during #187, however, since we want the global enable button to restore a disabled filter state, the `FilterState$enable` (#206) had to be rewritten to use single setters again.

**Comment by chlebowa** [comment]
For the record, `set_keep_na` and `set_keep_inf` are basically one-liners, moving their actions to `set_state` would actually decrease the code base, albeit slightly.

```
    set_keep_na = function(value) {
      checkmate::assert_flag(value)
      private$keep_na(value)
      logger::log_trace(
        sprintf(
          "%s$set_keep_na set for variable %s to %s.",
          class(self)[1],
          private$varname,
          value
        )
      )

      invisible(NULL)
    }
```
and then in `set_state`
```
          if (!is.null(state$keep_na)) {
            private$set_keep_na(state$keep_na)
          }
```

The getters are even shorter:
```
    get_keep_inf = function() {
      private$keep_inf()
    }
```

`set_selected` is a different matter.

**Comment by gogonzo** [comment]
We don't plan to do this. Thanks @asbates
