### ISSUE TITLE
Filter panel collapse icons can be incorrect

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#239]
Originally noticed in https://github.com/insightsengineering/teal.slice/pull/228#pullrequestreview-1363065122 . The collapse icons can get out of whack when disabling/enabling the filter panel.

Steps to reproduce:

1. Launch an app. For example, the CDISC example used in the filter panel refactor (https://github.com/insightsengineering/teal.slice/pull/165)
2. Collapse a data set filter section. (all filters for one data set)
3. Disable the filter panel
4. Enable the filter panel
5. Icon for step 2. is now incorrect.

![image](https://user-images.githubusercontent.com/36482959/228600424-9fa7a4b2-d473-4ec4-b482-24969bf97a03.png)

**Comment by chlebowa** [comment]
I notice that
1. reenabled filters always come back unfolded, whether or not they were collapsed on disable
2. when one 
a. collapses active filter variables for one dataset
b. clicks the global disable button
the collapsed section unfolds for a brief moment before disappearing as the filters are disabled.

Might this be a clue?

**Comment by asbates** [comment]
Yes, good eye. I think there's potentially a few issues with all this interactivity.

I do know that on global enable, new FilterState(s) are made and re-inserted. This is why the 'state' of each dataset section and each card is not restored on global enable. Now that we have single filter disabling though, this should be an easy fix. And remove some code to boot :)

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* Investigate why the chevron icon does not get reset when filter states are being reinstates
* If this require major changes, we'll wait until we complete #206

**Comment by chlebowa** [comment]
Initially I thought this can be easily fixed by adding a `toggle_icon` call to one observer but unfortunately it is not that simple.

Perhaps #206 will make this easier.

**Comment by chlebowa** [comment]
Update: #206 will not fix this. I don't know what triggers the accordions to unfold.

**Comment by chlebowa** [comment]
Confirmed, no disable, no problem.
