### ISSUE TITLE
Update vignette `Filter panel for NEST developers`

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#248]
### Summary
We need to update the vignette to better explain the current state of our filter panel.

### Acceptance Criteria
* Update content in general to make sure it's up-to-date
* Provide updated class diagram for teal.slices
* Remove/Update content related to Queue: 
  * Related task: insightsengineering/teal.slice#170

**Comment by chlebowa** [comment]
Done in #52
