### ISSUE TITLE
Rework on filter UI for logical variables

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.slice#250]
Currently filter selection UI for logical variables is using radio button. User has to pick either TRUE or FALSE, but not both.

![image](https://user-images.githubusercontent.com/78242757/233754826-3dda1c92-70e2-4ea7-8cdc-891d430335c2.png)

However, there will be use cases where user wants to filter data points to any non-NA values (both TRUE and FALSE, but exclude NAs). This is not possible with the current UI. 

Propose to use the same checkbox UI as factors with <N levels.

**Comment by gogonzo** [comment]
example app

```r
funny_module <- function(label = "Filter states", datanames = "all") {
  checkmate::assert_string(label)
  module(
    label = label,
    filters = datanames,
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_states")),
        verbatimTextOutput(ns("filter_calls")),
        actionButton(ns("reset"), "reset_to_default")
      )
    },
    server = function(input, output, session, data, filter_panel_api) {
      checkmate::assert_class(data, "tdata")
      observeEvent(input$reset, set_filter_state(filter_panel_api, default_filters))
      output$filter_states <- renderText({
        logger::log_trace("rendering text1")
        filter_panel_api |>
          get_filter_state() |>
          yaml::as.yaml()
      })
      output$filter_calls <- renderText({
        logger::log_trace("rendering text2")
        attr(data, "code")()
      })
    }
  )
}

options(teal.log_level = "TRACE", teal.show_js_log = TRUE)
options("teal.bs_theme" = bslib::bs_theme(version = 4))
# options(shiny.trace = TRUE)
pkgload::load_all("teal.slice")
pkgload::load_all("teal")
library(scda)

ADSL <- synthetic_cdisc_data("latest")$adsl
ADSL$logical1 <- FALSE
ADSL$logical <- sample(c(TRUE, FALSE), size = nrow(ADSL), replace = TRUE)
ADSL$logical[sample(1:nrow(ADSL), size = 10)] <- NA


default_filters <- filter_settings(
  filter_var(dataname = "ADSL", varname = "logical", selected = FALSE, fixed = TRUE),
)

data <- cdisc_data(
  cdisc_dataset("ADSL", ADSL)
)

app <- teal::init(
  data = data,
  modules = list(funny_module(), funny_module("module2")),
  filter = default_filters
)

runApp(app)

```

**Comment by asbates** [comment]
@gogonzo @chlebowa @donyunardi What do you think about using `ChoicesFilterState` for logical variables and removing `LogicalFilterState`? 

The way I see it is if we change from radio buttons to check boxes, then we are treating logical variables as categorical. So why not make that explicit. And that's one less class to maintain.

**Comment by donyunardi** [comment]
I support this.
I don't see a specific need for radio input, where only one value is allowed, so I have no objections to its omission.

**Comment by chlebowa** [comment]
There are other considerations:
* logical choices are always presented as "TRUE, FALSE", while factor choices are presented in alphabetical order
* logical selection defaults to TRUE, factor selection defaults to all levels
* `$get_call` is quite different for logical values

I don't think `ChoicesFilterState` can take over.

**Comment by gogonzo** [comment]
Issue will be addressed in https://github.com/insightsengineering/teal.slice/pull/296
