### ISSUE TITLE
Make `FilteredData` public

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.slice#26]
Copying from [my comment](https://github.com/insightsengineering/teal.transform/pull/51/files#r864526672)

We need to fix that at some point. It's impossible to construct a FilteredData object using the public API. At the same time:
* I have seen more than one instance of creating the object using calls to private functions in our examples or vignettes
 * module developers have access to the FilteredData object (when they develop a module) so its API is effectively public.

I think the easy fix is to just make the whole object public and be done with this weird charade.

**Comment by gogonzo** [comment]
From the documentation point of view this class is public - it's included in pkgdown and also `help(FilteredData)` shows documentation. We will downsize FilteredData to the minimum to not include information unneeded in the module (possibly remove shiny modules and methods handling stuff from DDL)
