### ISSUE TITLE
[Feature Request]: Drop unused levels in filtered datasets

### ISSUE THREAD

**Issue by mthbretscher** [insightsengineering/teal.slice#266]
### Feature description

I assume this belongs into teal.slice (possibly into another real-related package):

Several of teal.modules.clincal do not give meaningful results or show undesired behaviour if the filtered (adsl) dataset they run on contains factor levels that are not present the data. 
Examples: 
- tm_t_coxreg  and tm_t_logistic by default try to make treatment comparisons based on all defined factor levels in the treatment variable (I think taking the "first" factor level as reference, the others as comparators). This leads to an error ("Current ADSL data does not have observations from the reference and comparison treatments.") in both modules if any of those levels are not present in the filtered dataset. The app user must manually inspect his/her own filters and re-assign comparator/reference/unused factor levels before any regression result is displayed. Dropping non-existing factor levels should solve both these errors and increase usability considerably. 
- tm_t_coxreg attempts to estimate coefficients for all factor levels, present or not, resulting in coxph crashing.. Adjustment for variables where some levels have been removed by filtering can currently only be made using stratification (impacting functionality of the module)

I cannot think of a situation where non-existing factor levels could be needed, so such a change should not impact teal functionality in any negative way. On the other hand, dropping unused factor levels may have positive effects on usability of many modules, not requiring each module to ensure on its own that no non-existing levels are present. As an example, some versions of tm_g_km, when facetting, attempted to create a plot for all (including non-existing) factor levels. Updated versions now drop the non-existent factor levels. However, if this could be done already at teal.slice level, a lot of reduncancy could be avoided with each module doing this on its own.. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
This may have been fixed in https://github.com/insightsengineering/teal.slice/pull/261 but it's still in feature branch.
@mthbretscher do you have an example code that I can try?

**Comment by mthbretscher** [comment]
@donyunardi thanks for your reply.. I tried to get some simple toy code example together which would let you reproduce the problem & see whether it's already addressed by the abovementioned change (could be but not sure at all).

The problem is I ran into problems while creating the toy example & keep getting the same cryptic error.. and the hours went by, sigh.. At the end I decided to run the example code directly from the ?tm_t_logistic help page.. and even that one doesn't run & gives me the exact same error: `Warning: Error in <Anonymous>: Assertion on 'data' failed: Must inherit from class 'tdata', but has class 'list'.
  [No stack trace available]`
  
  ..without any indication of what the problem could be.. it's not module-specific, comes up with any module. 
  
  This is the code from the tm_t_logist help page which doesn't run:
  
  `library(scda)
library(dplyr)

ADSL <- synthetic_cdisc_dataset("latest", "adsl")
ADRS <- synthetic_cdisc_dataset("latest", "adrs") %>%
  filter(PARAMCD %in% c("BESRSPI", "INVET"))

arm_ref_comp <- list(
  ACTARMCD = list(
    ref = "ARM B",
    comp = c("ARM A", "ARM C")
  ),
  ARM = list(
    ref = "B: Placebo",
    comp = c("A: Drug X", "C: Combination")
  )
)

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL,
                  code = 'ADSL <- synthetic_cdisc_dataset("latest", "adsl")'
    ),
    cdisc_dataset("ADRS", ADRS,
                  code = 'ADRS <- synthetic_cdisc_dataset("latest", "adrs") %>%
        filter(PARAMCD %in% c("BESRSPI", "INVET"))' # nolint
    )
  ),
  modules = modules(
    tm_t_logistic(
      label = "Logistic Regression",
      dataname = "ADRS",
      arm_var = choices_selected(
        choices = variable_choices(ADRS, c("ARM", "ARMCD")),
        selected = "ARM"
      ),
      arm_ref_comp = arm_ref_comp,
      paramcd = choices_selected(
        choices = value_choices(ADRS, "PARAMCD", "PARAM"),
        selected = "BESRSPI"
      ),
      cov_var = choices_selected(
        choices = c("SEX", "AGE", "BMRKR1", "BMRKR2"),
        selected = "SEX"
      )
    )
  )
)

shinyApp(ui = app$ui, server = app$server)
`
  
If you'd happen to know what the problem might be then I should in a second step be able to produce some toy code to let you reproduce the problem..

**Comment by donyunardi** [comment]
Hi @mthbretscher 

First, if you're interested to try out the feature branch, please be sure to load:
1. the `filter_panel_refactor@main` branch for `teal` and `teal.slice`
2. latest main branch for `teal.transform`, `teal.widgets, `teal.data`, and `teal.modules.clinical`.

Secondly, I misunderstood the question in OP (apologies!) and I confirmed that the current behavior is to keep the unused levels in filtered datasets.

Here's a snippet code to confirm from the feature branch:
```r
var1 <- c("A", "B", "C")
mydataset <- data.frame(var1, stringsAsFactors = T)
levels(mydataset$var1) <- c(levels(mydataset$var1), "D") # Adding unused level
my_teal_data <- teal_data(dataset("mydataset", mydataset))
filtered_data <- init_filtered_data(my_teal_data)
fs <- filter_settings(
  filter_var(dataname = "mydataset", varname = "var1", selected = c("C"))
)
filtered_data$set_filter_state(fs)
isolate(filtered_data$get_data("mydataset")$var1)
```

![image](https://github.com/insightsengineering/teal.slice/assets/8597300/64e2a43b-85c3-4de4-8119-8681c584421b)

While I understand your argument, I personally believe that `teal.slice` should not drop unused factor levels without careful consideration based on the analysis at hand. Unused levels can be valuable during data exploration and visualization, as they offer insights into the dataset's structure and the potential range of categorical variable values. Additionally, preserving unused levels can be crucial for accurate modeling and data analysis, as it maintains the complete level structure. Considering these reasons, addressing the handling of unused factor levels within the teal module would likely be more appropriate.

**Comment by donyunardi** [comment]
I believe an alternative approach could involve considering the modules perspective, as you mentioned in the original post, where the newer version of the module now eliminates unused factor levels. To implement this, you can duplicate the base code of `tm_t_coxreg` and make necessary modifications to address your requirements, such as dropping unused or non-existent factor levels.

If this configuration is quite standard, we could consider adding this configuration to tmc and push your code there.

**Comment by mthbretscher** [comment]
Yes, that's what I'll do & will feed back any proposed code changes to the module developers
