### ISSUE TITLE
Remove get_formatted_filter_state and simplify format methods

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#267]
Format methods in all the classes should be an abstract method which should look like following:

```r
FilterState
format = function() {
  sprintf(
   "%s:\n%s",
    class(self)[1],
    format(self$get_filter_state())
  )
}
```

`get_filter_state` in `FilteredData` shouldn't return attr("formatted") as returned `teal_slices` has its own format method.

**Comment by m7pr** [comment]
closed with #281
