### ISSUE TITLE
FilterStateChoices - label is not present

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#271]
The variable label is not showing for COUNTRY column:
![image](https://user-images.githubusercontent.com/8597300/236945088-4dad1596-0f13-45a8-bec8-e13a8c614ac2.png)

The label for COUNTRY is `Country`.

Upon investigation, this line is dropping the `label` attribute from the column:
https://github.com/insightsengineering/teal.slice/blob/5d5d649e7ae26681d70a41bc709c72509c3a9f1e/R/FilterStateChoices.R#L156

This is what it looks like (before and after) when I filter the ADSL dataset using COUNTRY column:
![image](https://user-images.githubusercontent.com/8597300/236944496-dd6e1d96-0c67-4776-a6eb-6c2b6eb24bcd.png)

**Comment by asbates** [comment]
So here's what I found. `droplevels(x)` is just a call to `factor(x)`. So any additional attributes, in this case "label" are ignored. What we probably need to do then is something like

```r
label <- attr(x_factor, "label")
x_factor <- droplevels(x_factor)
attr(x_factor, "label") <- label
```

**Comment by donyunardi** [comment]
Yes, that does it.
Not sure if there's other elegant way to do this.
I'll create the PR for now.
