### ISSUE TITLE
[Bug]: change "remove" from actionLink to actionButton

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#278]
### What happened?

When filter panel is disabled there is still possible to remove `FilterState`, `FilteredDataset`, `FilteredData`. This happens because "global" disable doesn't apply to actionLink.

![image](https://github.com/insightsengineering/teal.slice/assets/6959016/a233cc43-f24d-4f06-8e74-916c184b4d75)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
The remove buttons were supposed to stay, this is not a bug.

**Comment by gogonzo** [comment]
Thanks @chlebowa
