### ISSUE TITLE
[Feature Request]: Implement "locked" to filter_var and FilterState

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#280]
### Feature description

This property would make filter unremovable from the filter-panel. Acceptance criteria:
- Argument `locked = FALSE` should be added to `filter_var`, `filter_expr` and to `FilterState$new`. 
- In `FilterState` remove button and disable button shouldn't be displayed when `locked = TRUE`
- In `FilterStates` we should prevent to remove all `FilterState` which have `locked = TRUE`

Voting results https://github.com/insightsengineering/teal.slice/discussions/283

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
I suggest "locked".

Since this filter state cannot be removed:
* can it be disabled?
* does it ignore the global disable switch?
* does is persist if "remove all filter states" is clicked for its parent data set?

I understand that `static = TRUE` ➡  `fixed = TRUE`

**Comment by asbates** [comment]
> I suggest "locked".

I like this as well.


> I understand that `static = TRUE` ➡ `fixed = TRUE` (for the purpose of UI and behavior).

I like "static" and would prefer it over "fixed".

> Also, use a different icon to the one used in fixed filters.

I think the current icon, a lock, most obviously goes with a "locked" filter.

**Comment by lcd2yyz** [comment]
> * `fixed` (already implemented) - not interactive filter (user can't change what is selected)

I personally still prefer `fixed` over `static`, although I'm open to having a vote and go with the more popular opinion.
For icon, what about an anchor?
![image](https://github.com/insightsengineering/teal.slice/assets/78242757/f45dbff8-eb3e-4cd4-be63-1976ad6bfb6b)


> * `unremovable` (locked) - filter which can't be removed or disabled.

For `unremovable`, can user still interact with the filter and change the selected value, even if the filter cannot be removed or disabled? If so, then `locked` sounds too strong.
What about `pinned` for filters that cannot be removed or disabled, but still can be interacted with? 
We can use this icon
![image](https://github.com/insightsengineering/teal.slice/assets/78242757/b16188b1-d48b-46f4-85ad-094bc9215d9d)


`locked` filter to me would mean fixed + unremovable = cannot change value nor remove nor disable.
One potential concern is whether uses will be able to grasp the difference and not get confused with 3 different icons.

**Comment by gogonzo** [comment]
I've created two polls 

- for "unremovable" https://github.com/insightsengineering/teal.slice/discussions/283
- for "fixed" https://github.com/insightsengineering/teal.slice/discussions/282

**Comment by chlebowa** [comment]
Sorry for the confusion, I was considering "static" for the new feature, then decided on "locked" but ended up typing out both. I'll make my case in the polls.

I understand that the new filter type cannot be removed, disabled, or modified by the user in any was whatsoever.

I don't like the anchor, to me it implies that one has stopped temporarily but will eventually depart.

"Pinned" is commonly used for "make this element show up at the top of the list and not fade into history", I don't think this would be a good name or icon here.

**Comment by chlebowa** [comment]
But it cannot be unpinned. I am mulling over "base filter" but that's not quite it, either.

**Comment by m7pr** [comment]
closed with https://github.com/insightsengineering/teal.slice/pull/297
