### ISSUE TITLE
Keep NA call for ChoicesFilterState may be wrong

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#284]
I don't think the keep NA call is right, at least for categorical variables. As an example, take the CDISC app in #165 and consider the variable `categorical`. This variable does have some `NA` values so if the keep NA checkbox is not checked, shouldn't the call have a `!is.na(categorical)` expression? This should be there regardless of what combination of non-NA values are selected, even if none.

**Comment by chlebowa** [comment]
covered by #402
