### ISSUE TITLE
disabled inputs are not disabled

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#294]
`private$ui_inputs` in some classes contains a line like this:
`if (shiny::isolate(private$is_disabled())) ui_input <- shinyjs::disabled(ui_input)`

I understand it is there to solve the following problem:
The UI of filter cards is only rendered when the card first becomes visible, i.e. when it is expanded. It can then be disabled by `shinyjs::disable`. However, if a `FilterState` is to begin the session in disabled state, the UI receives the `disable` command before it is rendered and thus ignores it. Adding a `disabled` call should force the input to be rendered disabled.

It doesn't work. Input widgets begin the session in enabled state:
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/fa0292f8-b396-418c-8bb7-4d76329bc46f)
(The plot looks disabled but that is controlled by a different mechanism.)

Once this is solved, it should be applied to all children of `FilterStates`.

### sessionInfo() (excerpt)

```R
R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

other attached packages:
 [1] teal.slice_0.2.0.9029     plotly_4.10.1             ggplot2_3.4.2             shinyjs_2.1.0             scda_0.1.6.9000          
 [6] teal_0.12.0.9026          teal.transform_0.2.0.9012 magrittr_2.0.3            teal.data_0.1.2.9013      testthat_3.1.7           
[11] shiny_1.7.4
```

**Comment by chlebowa** [comment]
This was touched on [before](https://github.com/insightsengineering/teal.slice/issues/241)

**Comment by gogonzo** [comment]
Not relevant anymore after https://github.com/insightsengineering/teal.slice/pull/300
