### ISSUE TITLE
Aesthetics of range selector and UX review

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.slice#320]
If we decides to go with `plotly` range selector https://github.com/insightsengineering/teal.slice/pull/289, few aesthetics needs to reviewed together with the new filter panel UX review https://github.com/insightsengineering/nestdevs-tasks/issues/27

- Look/feel of histogram plot - height, binning, size
- Use the same two-tone colors for the categorical count horizontal bar char (dark vs light colored)? Currently the histogram is showing color vs grey
- Spacing/margin around the plot and range selector UI

To be refined later..

**Comment by chlebowa** [comment]
> * Use the same two-tone colors for the categorical count horizontal bar char (dark vs light colored)? Currently the histogram is showing color vs grey

Please explain, do you want to use the histogram colors **for** the count bars or use the same color **as** the count bars for the histogram?

**Comment by chlebowa** [comment]
More issues:

+ question mark icon is partially obscured by the white mask imposed on a disabled plot; if the style of the containing div is modified with `position: relative; z-index: 9;`, it is brought to the from but it is still text on a transparent background, so the border of the mask still cuts through the icon; moving the icon lower with `margin-bottom: -1em;` is not the solution as it places the icon too low and makes it interfere with plot actions

**Comment by lcd2yyz** [comment]
> > * Use the same two-tone colors for the categorical count horizontal bar char (dark vs light colored)? Currently the histogram is showing color vs grey
> 
> Please explain, do you want to use the histogram colors **for** the count bars or use the same color **as** the count bars for the histogram?

The latter: use same color as the count bars for the histogram. 
But this is just my preference, I would definite like to get a UX designer at some point.

**Comment by gogonzo** [comment]
addressed
