### ISSUE TITLE
filter-card-title is partially covered by the disable switch

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.slice#336]
As per  @chlebowa  finding , it has been observed that the variable label in the first card is being partially obscured by the disable switch. Although this specific concern will be resolved soon with the removal of those switches in branch 135, the core issue persists. The problem lies in the rendering order of the div elements involved. The div containing the switch and the x mark `(filter-card-controls)` is displayed on top of the div containing the header` (filter-card-title)`. This leads to unintended visual overlap, impacting the usability and aesthetics of the interface.

![image](https://github.com/insightsengineering/teal.slice/assets/6700955/b6201f75-eaea-49ca-a176-a5499e7c6dd9)

**Comment by kartikeyakirar** [comment]
The issue of overlapping elements occurs only when the screen is minimized to a certain size. To demonstrate this behavior across resizing screen sizes, I have created a demo video showcasing the overlapping issue. I think we should consider and discuss the expected behavior of the interface across all screen sizes. 

https://github.com/insightsengineering/teal.slice/assets/6700955/616e226a-42c9-4759-860e-772e8f44698c

**Comment by gogonzo** [comment]
Not relevant anymore after https://github.com/insightsengineering/teal.slice/pull/300
