### ISSUE TITLE
[BUG] Forbid `teal_slices` for `excluded_varnames`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#340]
`teal_slices` has `included_varnames` and `excluded_varnames` argument which says which variables can be added as filters.
There is a possibility in `teal_slices` to specify `teal_slice` for `varname` which can't be filtered. Please make a proper assertion.

```r
teal_slices(
  teal_slice(dataname = "iris", varname = "Sepal.Length")
  exclude_varnames = list(iris = "Sepal.Length")
)

teal_slices(
  teal_slice(dataname = "mae", varname = "age"),
  teal_slice(dataname = "mae", experiment = "experiment", varname = "gene.id"),
  exclude_varnames = list(
    mae = list(subjects = "age", experiment = "gene.id")
  )
)

```

**Comment by gogonzo** [comment]
I think we need to close this issue as we can't control slices for all types of datasets. `teal`'s objective is to be data-type independent, so relying on `experiment` and `arg` (both are passed through `...`) shouldn't happen.

**Comment by kartikeyakirar** [comment]
Alright!
