### ISSUE TITLE
audit `FilterState$set_selected`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#350]
`$set_selected` involves multiple steps of validating the selected value. Investigate whether all of those steps are strictly necessary. `$cast_and_validate` and `$validate_selection` are at least partially redundant.

Start by understanding `$set_selected` and the methods that it calls.
Compare across subclasses.
Remove unnecessary methods/functions.

**Comment by m7pr** [comment]
you may want to consider removing `array` in favour of `vector` with this PR 44db769511f06101673cffbb89d03799bc729489
