### ISSUE TITLE
Rename `module_add` to `allow_add` in `filter_settings` 

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.slice#355]
**extension to issue**: https://github.com/insightsengineering/teal.slice/issues/330
Voted in https://github.com/insightsengineering/teal.slice/discussions/356

Please change argument name `module_add` to `allow_add` in `filter_settings`. Same change should be done in `teal::teal_filters`

**Comment by chlebowa** [comment]
I wholeheartedly agree! Thank you for raising this.
My suggestions would be:
`allow_more`
`allow_add`
`allow_filters`
`add_filters` (I like this one slightly less)
Among your suggestions I like `hide_add` the best, `hide_add_filters` would probably be even better.
