### ISSUE TITLE
Change argument name from locked to anchored

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#362]
Acceptance criteria
- change argument name in `teal_slice` from `locked` to `anchored`. 
- also change the appereance of the filter-card to display 

    - [lock](https://fontawesome.com/icons/lock?f=classic&s=solid) fixed 
    - [anchor](https://fontawesome.com/icons/anchor?f=classic&s=solid) when anchored
    - [anchor locked](https://fontawesome.com/icons/anchor-lock?f=classic&s=solid) when anchored and fixed

**Comment by chlebowa** [comment]
Are we sure about these names?

**Comment by gogonzo** [comment]
@chlebowa As of now me and @lcd2yyz are sure and confident. `locked` isn't accurate and `lock` icon for both `fixed` and `locked` is misleading. Having `anchored` and `fixed` arguments have icons which exactly reflects arguments.

**Comment by chlebowa** [comment]
![Screenshot from 2023-06-27 09-03-54](https://github.com/insightsengineering/teal.slice/assets/114988527/19223ae8-565a-4541-9281-4ad4c9536b5d)
