### ISSUE TITLE
Change argument `datalabel` to `experiment`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#364]
When specifying `filter_var` for MAE object we shouldn't use `datalabel` to determine which slot it refers to. 

1. `datalabel` can have following values:
- `filter_var(..., datalabel = "subjects")` to indicate that filter applies to the `colData`
- `filter_var(..., datalabel = "<experiment name>")` to indicate thayt filter applies to the experiment

Instead we should create this as follows:
- `filter_var(...)` - refers to subjects
- `filter_var(..., experiment = "<experiment name>"`) - refers to particulat experiment

2. If experiment is of `SummarizedExperiment` class, then we should add `arg`
- `filter_var(..., experiment = "<some SE experiment>", arg = "select")` - to filter by samples
- `filter_var(..., experiment = "<some SE experiment>", arg = "subset")` - to filter by genes

@danielinteractive are you fine with (2)? Example `teal::init(filter =)` would look like:
```r
default_filters <- filter_settings(
  filter_var(dataname = "MAE", varname = "race"),
  filter_var(dataname = "MAE", experiment = "some experiment", arg = "subset", varname = "x"),
  filter_var(dataname = "MAE", experiment = "some experiment", arg = "select", varname = "y")
)


```

**Comment by chlebowa** [comment]
`subjects` is not an experiment name, though, will it not be misleading?

**Comment by lcd2yyz** [comment]
> I wonder though that if we should try to more decouple the MAE and SE processing into separate package or directly into teal.modules.hermes and helios?

Thanks for the suggestion @danielinteractive
I too have been debating about how to best handle the specification for MAE data. We are adding two additional arguments `experiment` and `arg` to accommodate MAE object, but what if there are other S4 data classes, like just `SummarizedExperiment` or `DESeqDataSet`, such parameterization may not be relevant anymore.

Should we consider to keep the `filter_var()` function more generic for all potential datatypes, and move the evaluation of such more complex datasets to downstream processing (eg. `teal.data`?). So ultimately, we can have something like this... 

```
default_filters <- filter_settings(
  filter_var(dataname = "MAE", varname = "race"),
  filter_var(dataname = "MAE", varname = "some_experiment$[subset]$x"),
  filter_var(dataname = "MAE", varname = "some_experiment$select$y")
)
```

**Comment by gogonzo** [comment]
> Should we consider to keep the filter_var() function more generic for all potential datatypes, and move the evaluation of such more complex datasets to downstream processing (eg. teal.data?). So ultimately, we can have something like this...

```r
default_filters <- filter_settings(
  filter_var(dataname = "MAE", varname = "race"),
  filter_var(dataname = "MAE", varname = "some_experiment$[subset]$x"),
  filter_var(dataname = "MAE", varname = "some_experiment$select$y")
)
```

@lcd2yyz Each argument passed through `filter_var` is handled for many purposes such as constructing calls and displaying shiny output. `dataname`, `varname`, `experiment` and `arg` are used to create a SummarizeExperiment subset call in following way:
```r
<dataname>[[<experiment>]] <- subset(<dataname>[[<experiment]], <arg> = <varname> %in% c(<selected values>))
```
Proposed way to concatenate `varname = "experiment$select$y"` will require parsing `varname` and deducting what parsed elements exactly are.


`filter_var` have following arguments:
- dataname,
- varname,
- id,
- choices = NULL,
- selected = NULL,
- keep_na = NULL,
- keep_inf = NULL,
- fixed = FALSE,
- locked = FALSE,
- multiple = TRUE,
- ...

This means that any extension of `R6` classes can use custom arguments passed by `...`. This gives us possibility to develop new R6 classes without changing "generic" `filter_var` or `filter_expr`.

There are two possible solutions to handle MAE:
1. Move MAE stuff to the package like `teal.modules.hermes` or `teal.modules.helios` and create new `tmh::filter_var` and `tmh::filter_expr` there with `experiment` and `arg` being a formal argument.
2. Alternatively, we can have `teal.slice::filter_spec` function to encompass `filter_var` and `filter_expr` so in other packages one can do:
```r
filter_spec_mae <- function()
# instead of 
filter_var_mae <- function()
filter_expr_mae <- function()


filter_spec_mae_se <- function()
# instead of 
filter_var_mae_se <- function()
filter_expr_mae_se <- function()


filter_spec_mae_rse <- function()
# instead of 
filter_var_mae_rse <- function()
filter_expr_mae_rse <- function()
```

Me and @chlebowa supporting (2)

**Comment by chlebowa** [comment]
For the sake of clarity,
+ `filter_var` creates an object that merely **describes** a single filter state. It does not process or evaluate 
anything.
+ We are not adding arguments, actually. Any number of features can be passed to the `...` argument in `filter_var` and we handle those features appropriately within `FilteredData`. `datalabel` and `arg` are optional fields that will only be relevant if the dataset specified in `dataname` is a `MultiAssayExperiment`.

**Comment by chlebowa** [comment]
(posted at the same time as @gogonzo)

**Comment by lcd2yyz** [comment]
> 1. Move MAE stuff to the package like `teal.modules.hermes` or `teal.modules.helios` and create new `tmh::filter_var` and `tmh::filter_expr` there with `experiment` and `arg` being a formal argument.

I like this! Makes sense and keep package dependencies nicely controlled. Let's park this idea for later.

Thanks both for the explanation. Let's move forward with the `experiment/arg` proposal. Thanks!
