### ISSUE TITLE
remove `slices_field` function

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#381]
Remove the function `slices_field` from the package and replace it with appropriate `vapply` or `lapply` calls to `[[`, e.g.
```
slices_field(slices, "experiment")
unique(vapply(slices, `[[`, character(1L), "experiment"))
```

**Comment by m7pr** [comment]
@chlebowa slices_field is lit! IMHO slices_field is easier to read than unique(vapply(

**Comment by chlebowa** [comment]
I tend to agree but we decided to remove unnecessary sugar.

**Comment by kartikeyakirar** [comment]
Both unique(vapply(slices,[[, character(1L), "experiment")) and unique(unlist(lapply(slices, function(x) x[["experiment"]]))) are valid ways to find the unique experiments in a list of slices. However, there are some subtle differences between the two approaches.

The first approach uses the vapply() function to apply the [[ operator to each slice in the list, and then uses the unique() function to remove any duplicate values. This approach is more concise, but it can be less efficient if the list of slices is large.

The second approach uses the lapply() function to apply the x[["experiment"]] expression to each slice in the list, and then uses the unlist() function to flatten the resulting list of lists into a single list. This approach is less concise, but it can be more efficient if the list of slices is large.

<html>
<body>


Approach | Pros | Cons
-- | -- | --
unique(vapply(slices,[[, character(1L), "experiment")) | More concise | Less efficient for large lists
unique(unlist(lapply(slices, function(x) x[["experiment"]]))) | More efficient for large lists | Less concise


</body>
</html>

any thoughts? @chlebowa @gogonzo

**Comment by chlebowa** [comment]
> but it can be more efficient if the list of slices is large.

I don't know about that :thinking: 

The rule of thumb is: always go with `vapply` unless you can't because some elements can return `NULL` and you get errors on `FUN.VALUE`, then go with `lapply`. You will find that all slices have `id` but not all have `experiment`, for instance.
