### ISSUE TITLE
consistent naming of internal functions in the filter panel API

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#382]
By @gogonzo [here](https://github.com/insightsengineering/teal/pull/859)

> Now we have store, restore, as.list, slices_to_list, as.list, reassemble, disassemble. We need to figure out consistent way of converting slices to list and oposite.

There are a number of internal functions that deal with `teal_slice` and `teal_slices` objects and their names have become somewhat inconsistent. Discuss and revise the naming convention. Note the differences between to and from list conversions as there are several.

Remember, some of these functions are duplicated in `teal`.

**Comment by gogonzo** [comment]
Here is a design how in my opinion it should work.

![local-filter-panel-Page-14](https://github.com/insightsengineering/teal.slice/assets/6959016/659f50bf-8dbb-40f6-9d30-8190af0b883a)


1. There should be a method`as.list.teal_slices`
```r
as.list.teal_slices <- function(x, ...) {
  slices_list <- lapply(tss, as.list)
  attributes(slices_list) <- attributes(unclass(tss))
  slices_list
}
```
2. list produces by `as.list.teal_slices` can be used in snapshot
3. `format.teal_slices` can call `as.list.teal_slices` and convert it to the "restorable" `list(slices = ..., attributes = ...)`
4. `store` can be left unchanged
5. `restore` can be left unchanged

**Comment by chlebowa** [comment]
I don't entirely understand the figure, so let me summarize the current implementation and go from there:
`teal_slices` is saved by `teal_slices` |> `format` (`slices_to_list` |> `jsonify`) |> `slices_store`
`teal_slices` is loaded by `<file?` |> `slices_restore`
snapshot is created by `teal_slices` |> `disassemble_slices` |> add to list in `reactiveVal`
snapshot is restored by `<snapshot>` |> `reassemble_slices`

ad 1. The class has to be dropped before `lapply` to avoid that recursive loop.

So, `as.list.teal_slices` should basically be the same as `disassemble_slices`, right?
I was tempted to do that but I wanted to avoid confusion with `slices_to_list`. 

You are suggesting to remove `slices_to_list` as a separate function, correct? Attributes would be packed into a list with slices within `format`? I support this.

`reassemble_slices` is still necessary and since it is the reverse of `disassemble`, I kind of feel safer by adding that special class there. On the other hand, we only do this internally, so maybe we don't need that extra security.

It then becomes tempting to have `as.teal_slices` to do the job of `reassemble_slices` but that function already exists - it is the temporary solution for converting old filter specification (nested list) to `teal_slices`.

Btw., I tried handling disassembling and reassembling with `unlist`/`relist` but failed.

**Comment by m7pr** [comment]
Remember that in 

```{R}
as.list.teal_slices <- function(x, ...) {
  slices_list <- lapply(x, as.list)
```
you need to use `lapply(unlist(x), as.list)` because `lapply` uses `as.list` and you would end up in the infinite loop

**Comment by chlebowa** [comment]
Blocking until #298 is completed.

**Comment by chlebowa** [comment]
I am afraid we have to discuss this issue further.

`lapply` calls `as.list` on X. If `as.list` for `teal_slices` runs `as.list` on its elements, every time we run `lapply` on `teal_slices`, we operate on list representations of its `teal_slice` components, not on `teal_slice` objects. This is fine for extracting fields but `lapply` is used to pass `teal_slice` objects to `FilterState` constructors and the whole filter panel falls apart.

What we actually need is `as.list.teal_slices` that will only drop the `teal_slices` class and another function that will run `lapply(tss, asl.list)` to create a "disassembled" `teal_slices`.

**Comment by chlebowa** [comment]
OK, I made two adjustments:

1. `as.list.teal_slices` has an extra argument, `total = FALSE`, which specifies, whether to convert to list only the top layer (`teal_slices`) or also the bottom layer (`teal_slice` objects within). An alternative name for this argument would be `recursive`.
2. `as.teal_slices` accepts a list of lists and now those lists can, but need not, be `teal_slice` objects.

Seems to be working fine.

**Comment by m7pr** [comment]
I would opt for `recursive` instead of `total`

**Comment by chlebowa** [comment]
That was my first thought, actually, but `recursive` is an argument in `unlist` so this would be easier to find. The thing is the function is defined in `teal.slice` but will also be used in `teal` so in the moment it made sense to me to make it stand out a little.

I don't mind changing it to `recursive`.
