### ISSUE TITLE
[teal.slice] Why does teal_data have Subject if all datasets are not cdisc/mae

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#4]
![image](https://user-images.githubusercontent.com/15201933/159899437-067ea052-fdaa-48de-83e3-6ea51b647147.png)

```
library(teal)

app <- init(
  data = teal_data(
    dataset("IRIS", iris),
    dataset("MTCARS", mtcars)
  ),
  modules = modules(example_module())
)

runApp(app)
```

When this is fixed you should update the screenshot in the teal getting started vignette

**Comment by gogonzo** [comment]
+ When none of the dataset has primary keys then display subjects and observations
+ When none of the dataset has no primary keys don't display subjects

**Comment by m7pr** [comment]
IMHO, this is already fixed on MAIN

<img width="955" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/133694481/b351c40a-2f6d-4c93-95d0-4b5f2d927f93">

**Comment by m7pr** [comment]
Also fixed that on [669_](https://github.com/insightsengineering/teal/pull/1253) with  fa3dc9c320a668ded703e329dfe6e080e9299e3e as there were changes that reverted that
