### ISSUE TITLE
filterable varnames not set properly in `SEFilterStates` (possibly more)

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#400]
On branch `main` one can set a filter on "ARRAY_TYPE" in the "RPPAArray" experiment in miniACC.
```
library(MultiAssayExperiment)
data(miniACC)

ts <- teal_slice("mae", "ARRAY_TYPE", experiment = "RPPAArray", arg = "subset")
tss <- teal_slices(ts)

fd <- init_filtered_data(
  list(
    mae = list(dataset = miniACC)
  )
)

fd$set_filter_state(tss)
fd$get_filter_state() %>% isolate
```
Note that the `teal_slices` returned at the end contains `include_varnames` that lists all names of `colData(miniACC)` but it does not list any variables of `colData` or `rowData` of experiments.

This has not been a problem so far, but in #393 we are adding a check to the `teal_slices` function that ensures filters are only defined for allowed variables. As a result, as this `teal_slices` object is constructed, the `teal_slice` coming up from the `SEFilterStates` for "RPPAArray" is checked against the `include_varnames`, but that only contains the variables from the `colData`. This, on branch `340_bug_teal_slices@main` the code above raises an error.

**Comment by gogonzo** [comment]
It's not a bug, it is a missing feature. I'm moving this for the future

**Comment by kartikeyakirar** [comment]
@gogonzo Will PR #393, which lacks the above feature, be blocked due to test failures? At the moment, it is passing the tests because I have eliminated` teal_slice("mae", "ARRAY_TYPE", experiment="RPPAArray", arg="subset") `from all the example and test code.

**Comment by gogonzo** [comment]
Ah, okey. Let me look at the code if we can quickly fix this issue

**Comment by chlebowa** [comment]
Changes required to fix this have been comitted to branch `340_bug_teal_slices@main` with a TODO note in `c.teal_slices`. Should we ever get back to this issue, start there.
