### ISSUE TITLE
Better rounding in sliders

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#41]
Surely we can do better than this @kumamiao, @gogonzo 

![image](https://user-images.githubusercontent.com/15201933/171363410-1276731f-5e12-4925-bb39-299726677023.png)

See maybe https://github.com/rstudio/shiny/issues/1006 and https://stackoverflow.com/questions/42675102/r-shiny-slider-input-round

**Comment by donyunardi** [comment]
* I think the problem could be on this line:
https://github.com/insightsengineering/teal.slice/blob/80aa3c2c6943fb41f5204edd0ff61a07b123c3c0/R/FilterState.R#L1403

    For `Sepal.Length`, the value of `pretty_range_inputs["step"]` is `0.05`.
    If I hardcode the value `0.05` directly to the `step` argument, the slider UI rounds better.
    I don't understand what causing this behavior.
    <img src="https://user-images.githubusercontent.com/8597300/187005874-a3990ecc-0320-464c-9f10-c7f677b0f695.png" width="60%" height="60%" />
    <img src="https://user-images.githubusercontent.com/8597300/187005755-05b21988-2ca2-4423-bff0-96f65d66865a.png" width="50%" height="50%" />



* I also tried to modify the value of `n` on this line:
https://github.com/insightsengineering/teal.slice/blob/80aa3c2c6943fb41f5204edd0ff61a07b123c3c0/R/FilterState.R#L1666
    For `Sepal.Length`, lowering it to `n = 25` makes a better slider rounding. Maybe we can set a better logic to define the right `n` value?

* Lastly, I removed the `step` argument completely and use shiny calculation:
    https://github.com/rstudio/shiny/blob/c21ba0baca5a3eeaeabbdbcb8e9e83a6bd9a0bb9/R/input-slider.R#L255-L274
    This also resulting in correct slider rounding.
