### ISSUE TITLE
[Bug]: Prevent to deselect any value in DateFilterState

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#429]
### What happened?

![image](https://github.com/insightsengineering/teal.slice/assets/6959016/297d1993-d273-4f66-b51a-e9291c599a65)

To reproduce please run the app and select one of date variables, instead of selecting values just hit backspace to delete start or end date - app crashes. 

Acceptance criteria:
- We need to show notification similar to [this](https://github.com/insightsengineering/teal.slice/blob/cf44c48feae4b314cd7feea82c606b08c86e969d/R/FilterStateDate.R#L347) and setting value back to the previous. 

- Please check also `DatetimeFilterState`, after deleting value "text" input stays empty but doesn't fail. Instead of empty value, previous datetime should be displayed

```
library(shiny)
library(scda)
library(scda.2022)
library(teal.data)
library(teal.transform)
pkgload::load_all("teal.slice")
pkgload::load_all("teal")
library(teal.modules.general)

ADSL <- synthetic_cdisc_data("latest")$adsl
ADTTE <- synthetic_cdisc_data("latest")$adtte
ADRS <- synthetic_cdisc_data("latest")$adrs


default_filters <- teal_slices(
  teal_slice(dataname = "ADSL", varname = "RACE", selected = character(0)),
  teal_slice(dataname = "ADSL", varname = "SEX", selected = character(0), multiple = FALSE)
)

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL),
    cdisc_dataset("ADTTE", ADTTE),
    cdisc_dataset("ADRS", ADRS)
  ),
  modules = modules(
    tm_variable_browser()
  ),
  # filter = default_filters
)

runApp(app)

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by kartikeyakirar** [comment]
> Please check also DatetimeFilterState, after deleting value "text" input stays empty but doesn't fail. Instead of empty value, previous datetime should be displayed

Hey, @gogonzo! The shinyWidgets::airDatepickerInput function is utilized within DatetimeFilterState. However, it lacks a return value – when the input field is cleared, it doesn't provide any output. Unfortunately, there's no apparent setting to configure it to return a value at-least I can not find it. making it challenging to observe the event and restore the previous value.

To address this, a potential solution would involve reworking the airDatepickerInput function and making updates to the associated JavaScript portion.

**Comment by kartikeyakirar** [comment]
> We need to show notification similar to [this](https://github.com/insightsengineering/teal.slice/blob/cf44c48feae4b314cd7feea82c606b08c86e969d/R/FilterStateDate.R#L347) and setting value back to the previous.

This is done
