### ISSUE TITLE
[Bug]: Filterpanel description overlap with rewind state button

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.slice#435]
### What happened?

A bug happened!

There is a bug within the `filterPanel `widget specifically related to the "`Active filter Variables`"  widget. When a column contains a lengthy description, it causes an undesirable overlap with both the `rewind state` and `restore original state `buttons.

<img width="363" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/6700955/bd918bc1-4dfa-4cba-880b-4aff16706d1e">

Steps to reproduce

-  open [exploratory](https://genentech.shinyapps.io/NEST_exploratory_main/) app
-  Go to DataTable tab
-  In ADSL dataset select TRT02P or SUBJID
-  Select or deselect some option

**Comment by chlebowa** [comment]
[well](https://github.com/insightsengineering/teal.slice/issues/336)
