### ISSUE TITLE
[Bug]: The RangeFilterState's x-axis tick labels are somewhat obstructed.

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.slice#436]
### What happened?

The range selector widget for numeric input partially blocks the x-axis tick labels, which could benefit from improved visibility.

<img width="330" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/6700955/5e4e325c-3ab0-4471-9023-d47502cad6ea">

**Comment by chlebowa** [comment]
I only see this when I zoom in with the browser.

100%
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/a7acb636-d9ab-422e-bcd8-49532a8af6e8)

110%
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/c2577e00-4b00-4c34-af9e-b10fc548afce)

120%
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/4ba49caa-15ac-4720-8735-20e3d1282f47)

**Comment by kartikeyakirar** [comment]
I can observe this  with 100% zoom on my laptop. Does the size of my laptop screen affect the partial obstruction on the display?

**Comment by kartikeyakirar** [comment]
@m7pr  and @averissimo  can also check this?

**Comment by m7pr** [comment]
I see this in the browser for zoom higher than 90%, where for 120% it even rotates axes' labels by 90 degrees

80%
![image](https://github.com/insightsengineering/teal.slice/assets/133694481/c55a4a8e-cedb-4463-8a3f-daeb31a08daf)


90%
![image](https://github.com/insightsengineering/teal.slice/assets/133694481/90eb72cd-30e6-499e-8067-74cce31bb191)


100%
![image](https://github.com/insightsengineering/teal.slice/assets/133694481/a61ea761-fec7-4954-8690-3b1df7b4dae5)


120%
![image](https://github.com/insightsengineering/teal.slice/assets/133694481/05ec59c5-5466-4e41-8f61-596ddf91805f)

**Comment by chlebowa** [comment]
:laughing:

**Comment by averissimo** [comment]
Linux / Firefox: never rotates the labels _(but that may just be due to few ticks)_ and only hides it on zoom levels > 100%

I second @chlebowa :laughing: 

![image](https://github.com/insightsengineering/teal.slice/assets/211358/4455920c-0bbc-44d5-a96c-dace0ffc02c7)

**Comment by averissimo** [comment]
With age it rotates the labels and starts to hide at different zoom levels _(no longer hides at 133% 🤯)_

![image](https://github.com/insightsengineering/teal.slice/assets/211358/3525fdf0-4bb6-4f27-b2e2-f1022cba957b)

**Comment by averissimo** [comment]
I tried in Chrome and release version of firefox (all with 100%) and can't replicate your issue @kartikeyakirar 

Only when resizing the window to smaller sizes I found it hiding the bottom part of the label (when rotating it)

![image](https://github.com/insightsengineering/teal.slice/assets/211358/67475b80-3d9e-4a6c-bdb0-e55dd43ad75b)

**Comment by kartikeyakirar** [comment]
Thank you, @averissimo, @chlebowa, and @m7pr, for testing this. We seem to have an issue as I can reproduce it, as can Marcin. Therefore, I will work on finding a solution and check if it can be fixed system-wide.

**Comment by kartikeyakirar** [comment]
Additional testing: I was testing this in my another window machine. and issue only occures above 125%
100%
![image](https://github.com/insightsengineering/teal.slice/assets/6700955/22a6c26b-fa99-4d7b-b3be-f7852b14a68b)

110%
![image](https://github.com/insightsengineering/teal.slice/assets/6700955/e52b8233-21a4-4eca-9b48-0951f359c3ea)

125%
![image](https://github.com/insightsengineering/teal.slice/assets/6700955/351594c0-79c0-40c5-ab99-b88031142c60)
