### ISSUE TITLE
[Bug]: Application Crashes and Throws Script Out-of-Bounds Error When Rewind State Button is Clicked Twice

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.slice#443]
### What happened?

There is a critical bug in the application where clicking the rewind state button twice consecutively leads to a complete application crash. Additionally, this action triggers a script out-of-bounds error, displaying the message:` "Warning: Error in [[: subscript out of bounds."` 

![image](https://github.com/insightsengineering/teal.slice/assets/6700955/9b29619a-f81a-4b02-bb24-ed5bfcdfd577)

![image](https://github.com/insightsengineering/teal.slice/assets/6700955/f845d057-985f-4a52-b00b-9f1d47f8781a)

**Comment by chlebowa** [comment]
I cannot reproduce this. Tested by running the app locally in my own environment, as well as [here](https://genentech.shinyapps.io/nest_exploratory_main/), in `distribution` module.

**Comment by kartikeyakirar** [comment]
Could you attempt double-clicking the button? I am able to replicate this behavior.

https://github.com/insightsengineering/teal.slice/assets/6700955/4ab76867-1393-451e-aa07-ba2f1e09cc5d

**Comment by chlebowa** [comment]
All right, I see this now but only in certain conditions. 1) You have to be at the bottom of the history. 2) Does not appear to trigger for numeric ranges.
Seems to be connected to insufficiently quick UI updates. The button should be hidden before you can click it again.

**Comment by kartikeyakirar** [comment]
> Does not appear to trigger for numeric ranges.

I am able to reproduce it for Numeric range as well. and I think its related to DT table https://datatables.net/manual/tech-notes/7

https://github.com/insightsengineering/teal.slice/assets/6700955/1b258523-61cb-4883-b18b-46f8cfc899a3

> Seems to be connected to insufficiently quick UI updates.The button should be hidden before you can click it again.


This will certainly solve the issue.

**Comment by chlebowa** [comment]
No, the DT thing is a separate issue.
