### ISSUE TITLE
unify use of `tags$*` across the package

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#445]
`shiny` functions that create `HTML` tags (re-exported from `htmltools`) can be used directly or as elements of the `tags` list: 
```
div("some content")
tags$div("some content")
```

In `teal.slice` most `div` calls are direct but `span` calls usually use `tags$`.
Pick one and apply throughout the package.

--------------------------------------------------
## similar changes done here as part of this PR
- [x] teal https://github.com/insightsengineering/teal/pull/1122
- [ ] teal.data (not required)
- [ ] teal.code (not required)
- [x] teal.transform https://github.com/insightsengineering/teal.transform/pull/203
- [ ] teal.reporter (not required)
- [ ] teal.slice  https://github.com/insightsengineering/teal.slice/pull/566
- [x] teal.widgets https://github.com/insightsengineering/teal.widgets/pull/230
- [ ] teal.logger (not required)
- [ ] teal.modules.clinical https://github.com/insightsengineering/teal.modules.clinical/pull/1098
- [ ] teal.modules.general https://github.com/insightsengineering/teal.modules.general/pull/708
- [x] teal.goshawk https://github.com/insightsengineering/teal.goshawk/pull/268
- [ ] teal.modules.helios  https://github.com/insightsengineering/teal.modules.helios/pull/124
- [x] teal.modules.hermes https://github.com/insightsengineering/teal.modules.hermes/pull/367
- [ ] teal.osprey https://github.com/insightsengineering/teal.osprey/pull/259

**Comment by kartikeyakirar** [comment]
The majority of common HTML tags are directly accessible through re-exports from the` htmltools` package, including but not limited to` a, br, code, div, em, h1 through h6, hr, HTML, htmlTemplate, img, includeCSS, includeHTML, includeMarkdown, includeScript, includeText, is.singleton, p, pre, singleton, span, strong, suppressDependencies, tag, tagAppendAttributes, tagAppendChild, tagAppendChildren, tagGetAttribute, tagHasAttribute, tagList, tags, tagSetChildren, validateCssUnit, and withTags.` However, certain tags like `td, tr, table,` and` label `are exceptions and used in `teal.slice`and are not re-exported in this manner; thus, they require `tags$ `prefix .

so for unifying I prefer to do prefix` tags$`  for all HTML tags  to ensures a standardized codebase.

WDYT?

**Comment by chlebowa** [comment]
It's probably the way to go.

**Comment by averissimo** [comment]
Good choice on the `tags` :+1:  it will be easier to migrate if we move to `shiny::` :smiling_imp:

**Comment by chlebowa** [comment]
> Good choice on the `tags` 👍 it will be easier to migrate if we move to `shiny::` 😈

You can do that next month :wink:

**Comment by m7pr** [comment]
we can re-migrate every month : P
