### ISSUE TITLE
bug in filter card reactivity

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#455]
Clicking filter card controls triggers toggling of the body.

https://github.com/insightsengineering/teal.slice/assets/114988527/d812f5e6-f74d-498c-b078-5fcbb0ca6db0

```
rm(list = ls())

options("teal.bs_theme" = bslib::bs_theme(version = 3))
devtools::load_all("../teal.slice")
devtools::load_all("../teal")
library(scda)


funny_module <- function (label = "Filter states", datanames = "all") {
  checkmate::assert_string(label)
  module(
    label = label,
    datanames = datanames,
    ui = function(id, ...) {
      ns <- NS(id)
      div(
        h2("The following filter calls are generated:"),
        verbatimTextOutput(ns("filter_states")),
        verbatimTextOutput(ns("filter_calls")),
        actionButton(ns("reset"), "reset_to_default")
      )
    },
    server = function(input, output, session, data, filter_panel_api) {
      checkmate::assert_class(data, "tdata")
      observeEvent(input$reset, set_filter_state(filter_panel_api, default_filters))
      output$filter_states <- renderText({
        logger::log_trace("rendering text1")
        stage1 <- filter_panel_api |> get_filter_state()
        stage2 <- lapply(stage1, as.list)
        stage3 <- yaml::as.yaml(stage2)
        stage3
      })
      output$filter_calls <- renderText({
        logger::log_trace("rendering text2")
        attr(data, "code")()
      })
    }
  )
}

Iris <- iris
levels(Iris$Species) #%<>% toupper()
Iris$Species2 <- Iris$Species
Iris$Species3 <- Iris$Species
Iris$Sepal.Length[1] <- NA
Iris$Sepal.Length[2] <- Inf
Iris$Species3[2] <- NA
attr(Iris[[1]], "label") <- "variable label"
attr(Iris[[2]], "label") <- "variable label"
attr(Iris[[3]], "label") <- "variable label"
attr(Iris[[4]], "label") <- "variable label"
data <- teal_data(
  dataset("iris", Iris),
  dataset("mtcars", mtcars)
)

default_filters <- teal_slices(
  teal_slice("iris", "Sepal.Length", fixed = FALSE, anchored = FALSE),
  teal_slice("iris", "Sepal.Width", sel = c(2.5, 4.0), fixed = FALSE, anchored = TRUE),
  teal_slice("iris", "Petal.Length", sel = c(4.5, 5.1), fixed = TRUE, anchored = FALSE),
  teal_slice("iris", "Petal.Width", sel = c(0.3, 1.8), fixed = TRUE, anchored = TRUE),
  count_type = NULL
)

app <- init(
  data = data,
  modules = list(funny_module(), funny_module("module2")), filter = default_filters
)

runApp(app, launch.browser = TRUE)
```

**Comment by vedhav** [comment]
Yeah, it expands and collapses for me too.

**Comment by donyunardi** [comment]
Yes, I can reproduce this as well.

**Comment by kartikeyakirar** [comment]
I'm also able to replicate this behavior myself. Another question I have pertains to the situation where a user clicks on "Restore State." Unlike the behavior of the "Rewind" button, the buttons don't disappear after being clicked. Would it be reasonable to expect this to be the default behavior for both buttons?


https://github.com/insightsengineering/teal.slice/assets/6700955/cee3a5eb-991a-43d4-a614-1e363639c308

**Comment by chlebowa** [comment]
Well, since I caused it, I will take it.

@kartikeyakirar The restore button sets the initial state and adds it to state history just like any other state, hence the user can rewind to the previous setting. both buttons disappear when the history is empty, which can only be achieved by rewinding to the initial state, past any other selections.

**Comment by kartikeyakirar** [comment]
Understandable. Each modification contributes to the evolving state history, including the ability to revert to previous states. 

Although it may sound far-fetched, I think that hiding the "restore" button once the initial or a specific state is achieved would significantly improve the user experience in terms of visibility.For example, if I see a rewind button but no restore button, I know that it is in its initial configuration. However, there are more changes in the rewind history.

What do you think about this?

**Comment by chlebowa** [comment]
I see your point but I think it is clearer to always have the same number of buttons, especially since the one that would appear and disappear would be the one on the right, so the one on the left would move.
