### ISSUE TITLE
update filter card summary

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#457]
The filter card summary put up by `ChoicesFilterState` is empty when no selection is made. As a result, the height of the card changes depending on the selection state. Perhaps there should be a note of some sort for no selection?

##### _current_
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/f00da3e3-741e-4d15-b278-921aa57918d6)

##### _proposed_
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/dd5bdf48-98da-4efa-9380-d86a2e5b54a9)

**Comment by lcd2yyz** [comment]
Good catch! I like the proposal.
Extending a bit further, no selection effectively mean 0 observation in filtered data => null analysis. I would suggest to highlight the "No selection" text somehow (eg. text in red with a caution sign beside it or something similar).

**Comment by chlebowa** [comment]
That wold be somewhat redundant, I think. We already list the numbers of observations in the Active Filter Summary:
![image](https://github.com/insightsengineering/teal.slice/assets/114988527/c760e8f1-84f7-4a66-bf7b-5d5f6c2c6174)
On top of that most outputs will raise validation errors stating that there are no data to work with.
