### ISSUE TITLE
[Bug]: `bslib::bs_theme` dev version has modified return value that will break `teal.slice`

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal.slice#466]
### What happened?

On `FilterState-utils` the method to determine the sass_file needs to be re-written as development version of `bslib` will break it

```R
  # locate file that describes the current theme
  ## TODO this is not ideal
  sass_file <- bslib::bs_theme()[["layers"]][[2]][["defaults"]][[1]]
  sass_file <- attr(sass_file, "sass_file_path")
```

### How to reproduce?

Install `bslib` development version `renv::install("rstudio/bslib")` and try to build the `filter-panel-for-developers.Rmd` vignette

> Error in readLines(sass_file) : 'con' is not a connection

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
It seems another layer of list has been added. All it takes to fix it is to index deeper.
```
sass_file <- bslib::bs_theme()[["layers"]][[2]][["defaults"]][[1]] # fails
sass_file <- bslib::bs_theme()[["layers"]][[2]][["defaults"]][[1]][[1]] #works
```
This is still not ideal and I would LOVE a better way.
