### ISSUE TITLE
`slices_restore` do not restore `factor` classes

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.slice#467]
### What happened?

Similarly to https://github.com/insightsengineering/teal.slice/issues/373 slices_restore restore `factor` as `character`

```r
x <- 
  teal_slice(
    dataname = "ADSL", 
    varname = "COUNTRY", 
    selected = factor(c('POLAND', 'SPAIN')), 
    fixed = TRUE
  )
class(as.list(x)$selected)
#> [1] "factor"

y <- teal_slices(x)
slices_store(y, file = 'test1.json')
z <- slices_restore('test1.json')
class(shiny::isolate(z[[1]]$selected))
#> [1] "character"
```

Potential fixes need to be provided in https://github.com/insightsengineering/teal.slice/blob/main/R/FilterStateChoices.R#L138
where `selected` or `choices` of class `factor` may be all transferred to `characters`. Check out what actions/changes does it populate in other parts of the tool

**Comment by chlebowa** [comment]
Oh no, we specifically want factors in many cases, so converting to characters is not a solution.

However, considering that `choices` and `selected` are characters even when `x` is a factor, is this an issue?

**Comment by m7pr** [comment]
@chlebowa I provided a PR yesterday that leaves factors as factors and characters as characters https://github.com/insightsengineering/teal.slice/pull/468

The idea listed in the description of this PR is outdated. Would you take a look at https://github.com/insightsengineering/teal.slice/pull/468 ?

**Comment by chlebowa** [comment]
I am :wink:

**Comment by m7pr** [comment]
@chlebowa the alternative that we discussed is provided in here https://github.com/insightsengineering/teal.slice/pull/469

**Comment by m7pr** [comment]
closed by https://github.com/insightsengineering/teal.slice/pull/469
