### ISSUE TITLE
Remove CodeClass from FilteredData

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#471]
CodeClass will be removed soon, if FilteredData have to keep a code from data loading stage then it should be a `character`. Consider if code from data loading stage have to be kept in FilteredData.

**Comment by chlebowa** [comment]
If we go with `(a) teal_data (b) -> (c) FilteredData (d) -> (e) teal_data (f)`, I don't see why we wouldn't keep the initial code from (a)  in `FilteredData`. Otherwise you would have to have another entity hold on to it at (c) and modify what comes out of `FilteredData` at (d).

Store as character, absolutely.

**Comment by gogonzo** [comment]
> Store as character, absolutely.

Good point. Sounds like `setMethod(get_code, "character")` will be needed

**Comment by chlebowa** [comment]
> Good point. Sounds like `setMethod(get_code, "character")` will be needed

I'm not sure what you mean.

**Comment by gogonzo** [comment]
Code needs to be provided somehow between teal early stages and srv_nested_tabs. `FilteredData` is the only object which is passed at this moment. If `FilteredData` will contain code (character) or if code (character) will be passed further we need a method which can subset character code for a specific datasets (because code will contain all datasets code).

Having ``get_code.character` will give us possibility to pass code as character everywhere and extract it when needed.

**Comment by chlebowa** [comment]
Would you not `get_code(<teal_data>, names = module$datanames)`?

**Comment by chlebowa** [comment]
Thoroughly discussed and clear :+1:

**Comment by m7pr** [comment]
Hey, this `get_code` will remain in `teal` or `teal.slice` ? 
Also, I understand we will remove `get_code` from `teal.data` completely? https://github.com/insightsengineering/teal.data/issues/173

**Comment by chlebowa** [comment]
There is `teal.code::get_code` and it's not going anywhere. `teal.data` will inherit this function along with the `qenv` class, perhaps we will have to re-export it.

**Comment by chlebowa** [comment]
All `get_code` methods currently defined in `teal.data` will be removed, I believe.

**Comment by m7pr** [comment]
Amazing. The less the better.
