### ISSUE TITLE
Implement new design of the filter panel

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#48]
- blocked by https://github.com/insightsengineering/teal.slice/issues/47

Implement the new look of the filter panel drawn in the linked issue.

Items to complete:
* https://github.com/insightsengineering/teal.slice/issues/129
* https://github.com/insightsengineering/teal.slice/issues/130
* https://github.com/insightsengineering/teal.slice/issues/131
* https://github.com/insightsengineering/teal.slice/issues/132
* #133

**Comment by donyunardi** [comment]
Promoting this card to a roadmap. This card should list smaller issues needed to implement the new design of filter panel.

**Comment by gogonzo** [comment]
I've created the milestone for this [here](https://github.com/insightsengineering/teal.slice/milestone/1). I'm closing this issue as it's too broad and we can follow the progress in the milestone
