### ISSUE TITLE
reevaluate `variable_types` function

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#507]
`variable_types` is a generic function with methods for `data.frame`, `DataTable`, `DFrame`, `matrix` and a `default` method.

Actually, the `default `method handles `data.frame`, `DataTable`, and `DFrame`, the methods for these classes merely call `default`. 
Q1. Why do these methods even exist?

The `matrix` method goes through all specified columns and gets their classes, which is redundant because a matrix is an atomic.
Q2. Is it really necessary to have a generic with five methods? Why not have a single function that asserts input type to be a data.frame-like or a matrix and have a single `if` condition in there? This would have the added benefit of failing on data types that are not explicitly supported.

Q3. Bonus question: What is a `DataTable` class?

**Comment by averissimo** [comment]
Q3: No idea. Typo for `S4Vectors::DataFrame`? regardless, any data.frame-alike is supported on your PR :+1:

**Comment by chlebowa** [comment]
Actually, I found it, `DataTable` is an abstract class in `S4Vectors` that `DataFrame` (indirectly) inherits from.

**Comment by averissimo** [comment]
That's some serious digging :exploding_head: as it seems as the class is no longer available


#### NEWS

![image](https://github.com/insightsengineering/teal.slice/assets/211358/e722042c-5c16-439f-b58a-23394e41334b)

**Comment by chlebowa** [comment]
Not serious enough, apprently :joy: I thought `RectangularData` inherited from `DataTable` "or something" and stopped at that :wink:
