### ISSUE TITLE
 internal function `topological_sort()` is defined in `teal.slice` and `teal.data`

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal.slice#516]
### What happened?

The` topological_sort` function is defined in both the [teal.slice](https://github.com/insightsengineering/teal.slice/blob/ea691771d192535bbacfa76117576e63a3332df0/R/FilteredData-utils.R#L194-L242) and [teal.data](https://github.com/insightsengineering/teal.data/blob/79d37932d21b52e21d69681de82ae156e55d307f/R/topological_sort.R#L12-L60) packages, sharing identical logic.

Should we utilize it in `teal.slice` by employing the` getFromNamespace()` function (pending feedback from CRAN for `teal.code`)? Alternatively, do we consider exporting this function in teal.data?

**Comment by chlebowa** [comment]
I assume you mean to place the `getNamespace` call in `zzz.R` in `teal.slice` like we do in `teal`.
While it would reduce code duplication and make changes easier, `teal` `Depends` on `teal.data` but `teal.slice` `Imports` `teal.data`. I am in two minds about this.

**Comment by kartikeyakirar** [comment]
Yes, however, the presence of the '`teal.data'` package in the import section of '`teal.slice`' triggers a note on `check()`. 

<img width="398" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/6700955/f33d7b4f-c7b0-4328-8f93-48aea313b219">

**Comment by chlebowa** [comment]
I don't see how this is related.

**Comment by kartikeyakirar** [comment]
my mistake, I am getting this note because the function `getFromNamespace()` not because of the package is in import.
