### ISSUE TITLE
filter calls in `FilterState`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#535]
The `is.na` flag is _always_ added to the filter predicate in `FilterState`, which is redundant when specific values are selected.
Did we mess something up in https://github.com/insightsengineering/teal.slice/pull/402? I remember the review was thorough, so this may be deliberate but I honestly forget. 
It doesn't break anything, the calls are valid.

```
filter_state <- ChoicesFilterState$new(
  x = c(LETTERS, NA),
  slice = teal_slice(varname = "var", dataname = "data", selected = "A", keep_na = FALSE)
)
isolate(filter_state$get_call())
```
```
!is.na(var) & var == "A"
```

**Comment by m7pr** [comment]
This is fine with what we stated. if we have a single selection, NAs in data na keep_na = FALSE than `!is.na(var)` should be returned.
Check this table
https://github.com/insightsengineering/teal.slice/pull/402#issuecomment-1649204484
and that's this cell
<img width="746" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/133694481/cbe273f4-c19d-4a6f-858d-571f41b916e4">

**Comment by m7pr** [comment]
And we later decided to return `!is.na(x)` also for multiple selection

```r
> filter_state <- teal.slice:::ChoicesFilterState$new(
+   x = c(LETTERS, NA),
+   slice = teal_slice(varname = "var", dataname = "data", selected = c("A", "B"), keep_na = FALSE)
+ )
> isolate(filter_state$get_call())
!is.na(var) & var %in% c("A", "B")
```

https://github.com/insightsengineering/teal.slice/pull/402#issuecomment-1659847958

**Comment by chlebowa** [comment]
Awesome, thank you :+1:

**Comment by m7pr** [comment]
no worries, thanks for double checking and flaggin!
