### ISSUE TITLE
Custom format method for ChoicesFilterState

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.slice#54]
The ChoicesFilterState does not have own format method. 
As a result the print is not looks elegant for it, unequally spaced.

![image](https://user-images.githubusercontent.com/10676545/175926211-58b0cfdf-ef51-40aa-97d8-2c616cc2a885.png)

**Comment by Polkas** [comment]
linked to https://github.com/insightsengineering/teal.reporter/issues/96

**Comment by chlebowa** [comment]
This looks familiar.
https://github.com/insightsengineering/teal.slice/issues/109

**Comment by donyunardi** [comment]
I agree with @chlebowa 
It looks like we already took care of this with #109.

@Polkas do you think we can close this?

**Comment by BLAZEWIM** [comment]
The difference is that in #109 formatting was taken care of by modifying parent class. This issue is about adding custom format method to ```ChoicesFilterState```. So it is not a must have, anyway the main problem, which is a long                                                                 that happen for factors is fixed.

**Comment by Polkas** [comment]
The task is already solved. But we could create a new issue to transfer format function to each State implementation class.

The base `FilterState` class is a core for many different classes which inherit from it. The diffrent FilterState classes like ChoicesFilterState has own implementation of e.g. format method. The current `FilterState` format function is shared by only two classes which inherit from it Logical and Choices State. Sometimes it is better to be a little bit less DRY and have better code organization. Here I will prefer to have own format methods for all State Classes to be consistent and transparent.
