### ISSUE TITLE
Refactor filter panel - summary and collapsible

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.slice#55]
Refactor the FilterPanel regarding the linkage with teal.slice and the collapse functionality.
We want to make the process more elegant and clear. More than that there could be a hidden problem with reactivity when closing and opening the Filter Panel or with  possible calls for filters from a module server function.

Take into account that https://github.com/insightsengineering/teal.slice/pull/60 is already merged.
We solve the problem only for active filter , sb have to check the influence on the main part of the FilterPanel.
If the main Filter UI does not need `shiny::outputOptions(output, "table", suspendWhenHidden = FALSE)` call too.

**Comment by kpagacz** [comment]
The hiding/showing of the filter panel itself is, unfortunately, working as intended because we made the state of this particular UI feature global across all modules (disregarding whether they actually show it or not). 

I will investigate the disappearance of the summary.

**Comment by kpagacz** [comment]
I can confirm the buggy behaviour is reproducible. Clicking on any input makes the Filter Overview show up again. I will dig deeper.

**Comment by kpagacz** [comment]
There is something fishy about the active_datanames reactive. Basically what happens is that FilteredData$srv_filter_overview does not trigger when in some scenarios. I do not know yet why.

**Comment by Polkas** [comment]
ahhhh this is why we have to revert the full input cycle.
There is a new datasets connected reactivity. Looks like the datasets instance is reactive by itself now.
@gogonzo
