### ISSUE TITLE
FilterState format for empty Filters

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.slice#56]
When we as for the styled FilterState ( the format print), we should get a simple Empty Filters when there are no Filters.
Currently we get a line for each dataset and the filter are black for them.

From

Filters for ADSL:
Filters for ADTTE:

To

Empty FIlters

**Comment by Polkas** [comment]
linked to https://github.com/insightsengineering/teal.reporter/issues/96

**Comment by mhallal1** [comment]
related to https://github.com/insightsengineering/teal.reporter/issues/120
