### ISSUE TITLE
CSS good practices

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#563]
Our CSS file includes multiple expressions like this:
`  color: var(--bs-body-color, #333333);`
`  background-color: var(--bs-gray-200, #e9ecef);`

Is overwriting theme colors the proper way to style our elements? Why are we replacing variable values with hard coded values? Should we not rather use the hard coded values directly?

**Comment by donyunardi** [comment]
`bs` are custom css values in Bootstrap so if I think this setup automatically change the UI colors for filter panel if they choose to use different Bootstrap themes.

It was added in #165 so maybe @gogonzo can confirm.

**Comment by chlebowa** [comment]
I don't think he will, styling was an afterthought in that PR :laughing:

**Comment by chlebowa** [comment]
I just realized I misunderstood the `var` function. Sorry for raising a ruckus.
