### ISSUE TITLE
[Bug]: Rewind the state of the filter does not rewind

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.slice#607]
Explored during https://github.com/insightsengineering/teal.gallery/tree/main/efficacy app testing for `669_insertUI@main` branch.

<img width="870" alt="image" src="https://github.com/user-attachments/assets/67a9710a-17c7-4d1b-b9e8-7072b9592369">

Removed a level on the filter

Then clicked `rewind`

<img width="216" alt="image" src="https://github.com/user-attachments/assets/5cac4913-bab0-4950-9e49-f5da7a312697">

And nothing was reverted (to the selection of both levels), but rewing button disappeared

<img width="242" alt="image" src="https://github.com/user-attachments/assets/b23d0338-8807-43fa-b255-8ea00fc4221f">

**Comment by m7pr** [comment]
This happens if you deslect the level and already try to rewind. If you keep selecting and deselecting the levels and after multiple attempts you go to the rewind, then it rewinds

**Comment by vedhav** [comment]
This might be related to the checkbox in the [feature branch PR](https://github.com/insightsengineering/teal/pull/1253#issue-2377238428).

> - [ ] the back and reset JS buttons are made visible during module init if the same filter cards are present in other module that was initialized. The [private$state_history()](https://github.com/insightsengineering/teal.slice/blob/4366cf9ad01a97210d03e4f776215a758e0b69ff/R/FilterState.R#L256) is changed because of other module, have to change the if condition for the toggle.

**Comment by m7pr** [comment]
Thanks, tested today and it's fixed!
