### ISSUE TITLE
Fix failed pipeline

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#614]
https://github.com/pawelru/ie_status?tab=readme-ov-file

**Comment by m7pr** [comment]
`teal.slice` failed becuase of `noSuggests` test failure. I'll take a look at this one once IDR eliminates the issue with GitHub credentials . Currently we exceed GitHub limits during dependenices installation. https://github.com/insightsengineering/teal.slice/actions/runs/10336794337/job/28612924156

![image](https://github.com/user-attachments/assets/0361cb53-8c7b-42bf-9bce-d2d254a3bf24)

**Comment by m7pr** [comment]
The pipeline does not raise issues if it's run alone, without any other jobs running at the same time that share github limits
https://github.com/insightsengineering/teal.slice/actions/runs/10383145531

**Comment by donyunardi** [comment]
min_cohort and min_isolate failed

min_cohort:
https://github.com/insightsengineering/teal.slice/actions/runs/10543899677/job/29212343007#step:9:54
```
Error in data.frame(type = "bioc", package = package, version = cran_current$version,  : 
  arguments imply differing number of rows: 1, 0
Calls: fun ... get_release_date.remote_ref_cran -> get_release_data -> data.frame
Execution halted
```

min_isolate:
https://github.com/insightsengineering/teal.slice/actions/runs/10543899677/job/29212343150#step:9:64
```
Error : ! Could not solve package dependencies:
* deps::/tmp/RtmpoiLZTL/filec2f625beb:
  * Can't install dependency bioc::MultiAssayExperiment
  * Can't install dependency bioc::SummarizedExperiment
In addition: There were 20 warnings (use warnings() to see them)
```

My first impression is that it doesn't seem to recognize or pull information from `bioc` (BioConductor).

**Comment by donyunardi** [comment]
@cicdguy @pawelru 
I'm going to play around with `verdepcheck` package but do you have any idea why the image failed to install bioc dependencies? Is `verdepcheck` compatible with `bioc` packages?

**Comment by pawelru** [comment]
The first one is definitely an error in versepcheck that is likely already fixed in one of the two PRs that are opened and waiting for a review. For the other one I will have to have a deeper look

**Comment by m7pr** [comment]
I just rerun failed jobs just in case to see if the BioC packages can be installed again https://github.com/insightsengineering/teal.slice/actions/runs/10603538113

**Comment by m7pr** [comment]
Since https://github.com/insightsengineering/verdepcheck/pull/56 verdepcheck issue got fixed and merged I started new pipeline https://github.com/insightsengineering/teal.slice/actions/runs/10632631907
