### ISSUE TITLE
Implement bindCache wherever possible to avoid unnecessary reactivity on "unfiltered" data.

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#62]
Implement bindCache for filter_panel to avoid triggering reactivity for every filter-panel change.

Reason to do this is because adding single filter-state which does nothing triggers the reactivity. We should avoid reactivity when code and parent data remains unchanged.

**Comment by gogonzo** [comment]
- Alternatively, please check if in FIlteredData there is some redundant reactivity which retriggers calculation (or shiny events) downstream. Check on in any tlg-module if adding/removing single (empty) filter state  causes extra reactivity event.

**Comment by nikolas-burkoff** [comment]
Remember that bind_cache will mean we'll need to add >= 1.6 for shiny for NEST

**Comment by gogonzo** [comment]
Please note that cache must be distinguished between sessions (not in globalEnv - not shared by different app users)

**Comment by kumamiao** [comment]
Will de-prioritize and keep open

**Comment by gogonzo** [comment]
addressed with latest teal refactor
