### ISSUE TITLE
Filter summary: unsupported datasets might take a lot of space

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.slice#621]
![image](https://github.com/user-attachments/assets/288da6f8-d062-447a-b7fc-3ccf1977b40e)

Please find a better way to handle these. Maybe an inform text below the table?

**Comment by averissimo** [comment]
This was implemented on #1393, closing the issue.

![image](https://github.com/user-attachments/assets/9fa6c00d-ba90-48a3-96a7-a7ccd32d436f)
