### ISSUE TITLE
[Bug]: teal pushes list of data which fails in data_merge 

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#68]
I'm posting issue here to highlight very important problem.

- in FilteredData we do following

```r
ADSL_FILTERED <- dplyr::filter(ADSL, <filter conditions>)
XXX_FILTERED <- dplyr::filter(XXX, <filter conditons>)
```

- teal returns a list of of filtered data named without suffix with code attribute. I can simplify this to:
```r
data <- structure(
  list(
    ADSL = <ADSL_FILTERED>,
    XXX = <XXX_ FILTERED>
  ),
  code = "
    ADSL_FILTERED <- dplyr::filter(ADSL, <filter conditions>)
    XXX_FILTERED <- dplyr::filter(XXX, <filter conditons>)
  "
)
```

- data is passed to the module and problems are more visible now. Module takes data (named ADSL, XXX), data_extract_spec, join_keys and tries to establish encoding panel. Here everything is fine as data, join_keys and data_extract_spec refer to a  basic names (ADSL, XXX)

```r
data_extracts <- data_extract_spec_multiple(data, join_keys, data_extract_spec, ...)
merged_data <- data_merge_module(data_extracts, data, join_keys, ...)
```

Then output from data_extract inputs is passed to the merge_module where we have a conflict of names being not compatible with the code. data_merge - produces following R code 

```r

ANL1 <- ADSL_FILTERED
ANL2 <- XXX_FILTERED
ANL <- merge(ANL1, AN2, ...)
``` 

Above lines can't be evaluated as we can't assign _FILTERED as we have only `ADSL` and `ADTTE`

Possible solutions: 
- we can pass the data from teal containing _FILTERED and unfiltered data. But the join_keys in data_merge are used with _Filtered. Also we don't want to bother user to specify data with filtered and unfiltered data.
- teal.slice to do `ADSL <- dplyr::filter(ADSL, <conditions>)`
- ....

**Comment by nikolas-burkoff** [comment]
So my gut feeling here is:

- As far as I'm aware we never use both the filtered and unfiltered data in the modules **at the same time** e.g. in data_table, variable_browser there is a switch as to whether we are using filtered or unfiltered data? 

If that's the case I would move the switch to the filter panel (a disable/enable) all filters switch which turns off/on all filtering without deleting all the filters. Then the modules only need either the filtered or the unfiltered data (If it's not the case I would think long and hard about why and if we can get around it - if modules are meant to work with just a list of data.frames then we have problems here anyway...)

- The modules should (must) not know anything about whether the data has been filtered or not - it should just receive some named datasets and those names are used throughout the module for data merge and in the join_keys etc.

- If you use modules outside of of teal::init and not using a filter panel then you are free to call your data.frames whatever you want

- If you use modules inside teal::init then I think the datasets being passed into the modules should be named XXXX_FILTERED and the filter panel can give you these names and an updated join_keys object with the appropriate names (if all filters are switched off then you could either just do ADSL_FILTERED <- ADSL and change things, or if we prefer just pass ADSL in instead.) 

I really do not like overwriting ADSL say ADSL <- dplyr::filter(ADSL, ...) because a) if you want to run two different SRCs one after the other it means you have to repull ADSL which could be expensive b) in the reporting we may want to in the future do some smarter grouping of SRC which is harder to do if ADSL is mutable c) this could get very complex with more sophisticated options in the filter panel in the future

- If you are using modules and filter panel outside of teal::init in your own app, it's up to you what you do - I suggest you copy how teal::init does it, whcih suggests we need some nice helper functions inside teal.slice to do this.

**Comment by gogonzo** [comment]
> As far as I'm aware we never use both the filtered and unfiltered data in the modules at the same time e.g. in data_table, variable_browser there is a switch as to whether we are using filtered or unfiltered data?

You are right, they are not used in the same time, but some modules need to have access to filtered and unfiltered at the same time because switch is inside of the module. But as you noted, we can move switch outside of the module and show either filtered or unfiltered data.

> If that's the case I would move the switch to the filter panel (a disable/enable)

----------------

> The modules should (must) not know anything about whether the data has been filtered or not - it should just receive some named datasets and those names are used throughout the module for data merge and in the join_keys etc.

I agree.

> If you use modules outside of of teal::init and not using a filter panel then you are free to call your data.frames whatever you want.

I agree. 

> If you use modules inside teal::init then I think the datasets being passed into the modules should be named XXXX_FILTERED and the filter panel can give you these names and an updated join_keys object (join_keys$set_suffix("_FILTERED")) with the appropriate names (if all filters are switched off then you could either just do ADSL_FILTERED <- ADSL and change things, or if we prefer just pass ADSL in instead.)

Yes, that's one of the solution, to change names to _FILTERED in `join_keys` object which is passed to ui_tlg_module and srv_tlg_module. We will need to change also `data_extract_spec` objects and `datanames` argument accordingly.

**Comment by gogonzo** [comment]
There are possible 3-scenarios:

1. teal to rename data_extract and join_keys entries from XXX -> XXX_FILTERED. Problem arises with data_extract which is in $server_args - so we need to find data_extract_spec$dataname and rename it...
2. teal.slice to overwrite ADSL <- filter(ADSL, <filters>) instead of creating a new dataset. It's a big change possibly breaking. Possibly because if somebody uses chunks environment - probably there was following:
```r
env$ADSL_FILTERED <- datasets$get_data("ADSL", filtered = TRUE)
chunks_reset(env)
```
3. Enable merge_expression_module to work with the `FilteredData` - evaluate `merge_expression_module$expr` in the chunks in the tlg module.


FilteredData is an evil incarnate 👿

**Comment by gogonzo** [comment]
I foresee possible problems doe to `ADSL <- filter(ADSL, <filter>)`:
1. Somebody uses chunks environment with ADSL_FILTERED
```r
ADSL_FILTERED <- datasets$get_data("ADSL", filtered = TRUE)
chunks_reset()
```

2. Somebody uses `ADSL_FILTERED` in chunks initialized with data_merge_module
```
chunks_push_chunks(merged_data())
chunks_get_var("ADSL_FILTERED")
```


I searched the internal GH + GL to see if the change could affect any code there. I don't think we have so much to choose.

**Comment by gogonzo** [comment]
Illustration from the yesterday's meeting:

![quosure-Page-9 (1)](https://user-images.githubusercontent.com/6959016/178945022-19778aa8-d80f-4e64-96ed-67cb1558b79b.jpg)



Little  code snippet to show the problem:

```r


options(teal.log_level = logger::TRACE)
devtools::load_all("teal")
#library(teal.modules.general)
library(scda)
#logger::log_threshold(logger::TRACE, namespace = "teal")

ADSL <- synthetic_cdisc_data("latest")$adsl
ADTTE <- synthetic_cdisc_data("latest")$adtte


adsl_module <- module(
  label = "ADSL module",
  ui =  function(id) {
    ns <- NS(id)
    div(
      h1("example module"),
      verbatimTextOutput(ns("code")),
      DT::dataTableOutput(ns("out")),
      selectInput(ns("button"), "select val", choices = c("a", "b"), selected = "a")
    )
  },
  server = function(id, data) moduleServer(id, function(input, output, session) {
    # if names are unchanged"
      # - evaluation succeeds as join_keys can be found by the names of the list
      # - show rcode is inexecutable
    # if names are changed to _FILTERED
      # - evaluation id wrong as merge(by = NULL) - can't find join keys to ADSL_FILTERED
      # - show rcode is working
    names(data) <- c("ADSL_FILTERED", "ADTTE_FILTERED")

    r1 <- reactive({
      data_flatten <- lapply(data, function(x) if (is.reactive(x)) x() else x)
      env <- list2env(data_flatten)
      env
    })

    merge_expr <- reactive({
      datanames <- names(data)

      # if datanames are filtered join_keys won't be matched
      jk <- attr(data, "join_keys")[[datanames[[1]]]][[datanames[[2]]]]
      
      rlang::expr(
        ANL <- dplyr::left_join(
          !!as.name(datanames[[1]]), 
          !!as.name(datanames[[2]]), 
          by = !!jk
        )
      )
    })
    

    r2 <- reactive({
      env <- r1()
      eval(merge_expr(), envir = env)
      env
    }) 

    output$out <- DT::renderDataTable(r2()$ANL)

    output$code <- renderText({
      paste(
        c(
          attr(data, "code"),
          deparse1(merge_expr())
        ),
        collapse = "\n"
      )
    })
  })
)

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL, code = "ADSL <- synthetic_cdisc_data('latest')$adsl"),
    cdisc_dataset("ADTTE", ADTTE, code = "ADTTE <- synthetic_cdisc_data('latest')$adtte"),
    check = TRUE
  ),
  modules = modules(adsl_module),
  filter = list(
    ADSL = list(
      SEX = list("M", keep_na = TRUE),
      COUNTRY = c("USA", NA),
      AGE = list()
    )
  )
)

runApp(app)

```

**Comment by gogonzo** [comment]
We have a conclusion here:
1. We overwrite datasets in the show R code in the `FIlteredData`
2. we pass the data as a list to the module
3. we pass `filter_panel_api` to the modules which contains `$get_unfiltered_data(dataname)`
4. in the tlg modules we can have `filter_panel_api = NULL` by default and modules should be  responsible of scenarios where filter-panel is enabled or not.
5. Another solution to (4) is `filter_panel_api = filter_panel_api()` which will be a default value to not break all the modules. But why to include ghost-class with dummy methods returning empty `list()` and append it to the reporter. In this case we probably should prefer (4)

**Comment by nikolas-burkoff** [comment]
5. Is better as otherwise everywhere there is a reference to filter_panel_api module developers will need to wrap it up.

If doing 4)

```
if(is.null(filter_panel_api))) {
  data[[dataname]]()
} else {
  filter_panel_api$get_unfiltered_data(dataname)
}
....

//reporter
if (!is.null(filter_panel_api) {
  card$add_text("Filter State")
  card$add_text(filter_panel_api$get_filter_state())
}

```

Or with 5)
```

filter_panel_api$get_unfiltered_data(dataname) #the dummy one returns just the data

....

card$add_text(filter_panel_api$get_filter_state()) # which returns empty string if dummy filter panel and includes FilterState heading
```

4) requires module developers to do more work...

**Comment by gogonzo** [comment]
Yup, I'm happy with (4) also.

_Side note: I have an impression that saving-and-restoring a filter-states for reporter sounds like some sort of the bookmarking. There might be more to research on this - settings (filter-states and encodings) need to be saved and restored which means that data need to be passed to reporter and also they need to find their way back to restore the states. My first thought is that shiny bookmarking is solved in the `session` but chunks story gives me reason to think three times before._

**Comment by gogonzo** [comment]
Ok, we decide to start doing this.
This will need to be highlighted in the communication for the next release to give instruction how to upgrade to a new version of NEST @kumamiao 
This change has two consequences for the modules from outside of insightsengineering:
1. Returned code won't be reproducible if chunks_push contains some `XXX_FILTERED` calls
2. Or/and app will fail if modules has a `<chunks>$get_var("XXX_FILTERED")` 

Any warnings won't be enough, because we can cover (2) but for (1) we would need to analyse chunks_push if it contains XXX_FILTERED in rhs.

**Comment by gogonzo** [comment]
Follow up issue to implement: 
https://github.com/insightsengineering/teal.slice/issues/76
