### ISSUE TITLE
[Feature Request]: Enable passing filters via a metadata file & display filter description on the filter panel (discussion)

### ISSUE THREAD

**Issue by kumamiao** [insightsengineering/teal.slice#72]
### Feature description

Purpose: Enable app developers to pass on a filter metadata file, which specifies the filter name and filter condition. This will comply with chevron design, and the filter panel with titles could be more intuitive for app users (end users who are not familiar with the data structure), and consistent with the analysis output (TLG) titles. This will help enable future `chevron_to_teal` development

Sample filter metadata: https://github.com/insightsengineering/citril.metadata/blob/main/inst/extdata/standard_filters_titles.yaml

- for filter that have title, display the title
- for filters that do not have title, display as ~ (target.condition)
- if app developer has passed a filter metadata, enable a toggle(?) in the filter panel UI to allow app end users to choose to display "filter condition" or "filter title"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by lcd2yyz** [comment]
Feature is achieved by https://github.com/insightsengineering/teal.slice/pull/262
