### ISSUE TITLE
Change returned filter panel code to avoid `_FILTERED` suffix

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#76]
$get_call should return following code 

```r
ADSL <- filter(ADSL, <filters>)
ADTTE <- filter(ADTTE, <filters>)
ADTTE <- inner_join(ADTTE, ADSL, by = <keys>)
...
```

This will require also to make a change in https://github.com/insightsengineering/teal.transform/search?q=_FILTERED

Please add NEWS.md entry under BREAKING CHANGE.

**Comment by nikolas-burkoff** [comment]
We should completely confirm that we are not releasing in aug before merging this in as until this, there weren't any breaking changes.

We should also (simultaneously fix teal.goshawk just [here](https://github.com/insightsengineering/teal.goshawk/blob/0cc0c83ec05c2a8aced53e58aa426cb3f22c5458/R/utils.R#L179) I think and teal.osprey (all over the place I'm afraid)

**Comment by gogonzo** [comment]
We are not release in Aug. Yes, teal.goshawk and teal.osprey should also be fixed

**Comment by pawelru** [comment]
@nikolas-burkoff please note that if we go fully with GitHub flow you would have to increase dependent package versions in your PRs

**Comment by nikolas-burkoff** [comment]
If we do that, then I guess we won't use staged.deps anymore as we'll need to manually handle deps on the branches

**Comment by gogonzo** [comment]
We merge to feature branch then?

**Comment by pawelru** [comment]
> If we do that, then I guess we won't use staged.deps anymore as we'll need to manually handle deps on the branches

Not exactly. I am thinking of CD here where after merge to main your changes would not be compatible with the initial (not changed) dependent package version.

An example to make it clear:
- at T0 we have:
  - package A of version 0.1.2
  - package B of version 1.2.3 that requires A >= 0.1.2
- after your the changes without dependents bump-ups
  -  package A of version 0.1.3
  - pacakge B of version 1.2.4 that requires A >= 0.1.2   -> bang!! the combination of A=0.1.2 is not compatible with B=1.2.4

staged.deps is a separate thing to use correct version within CI

> We merge to feature branch then?

If it is a part of a bigger refactor that requires some other PRs in the future to make it **complete** - yes.
