### ISSUE TITLE
Introduce disable filters in FilterPanelApi/FilteredData

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#84]
Please add option to disable filters for particular module. This particular module should get unfiltered data when toggle filter through FilterPanelApi

**Comment by nikolas-burkoff** [comment]
Should this be module specific? Isn't it easier for both app developers and app users to have one global toggle which turns the filter panel on/off for all modules? i.e. [here](https://github.com/insightsengineering/teal.slice/pull/91)

**Comment by donyunardi** [comment]
Hi @kumamiao, can you help us on this? Do you think user would prefer global on/off or module-level on/off? 
Or maybe both?

**Comment by kumamiao** [comment]
I feel like should we consider putting a hold on this issue, as we're planning for a bigger design change for the filter panel (which could potentially involve the setup for global & module-specific filters)?

**Comment by gogonzo** [comment]
@kumamiao we prefer to go through as we are working on the feature branch. This will be easier for developers to move forward with having quosure implemented in all modules. Disable/enable filters can be reverted and modified at any point.

**Comment by kumamiao** [comment]
In this case let's move forward with this issue. I would propose to go with what Nik suggested, have one global toggle which turns the filter panel on/off for all modules - although one concern here, if switched from on->off->on, would the default choices come back to previous selected filters, or everything would be wiped off?

In the future if we want to enable and then implement module-level toggle, then that toggle would be only applicable for module-specific filters and not impact global filters.

**Comment by nikolas-burkoff** [comment]
> although one concern here, if switched from on->off->on, would the default choices come back to previous selected filters, or everything would be wiped off? The former would be preferred if possible

So I agree when turning the filter panel back on - the filters which were active at the time the filter panel was turned off should be turned back on again - as is the case [here](https://github.com/insightsengineering/teal.slice/pull/91)
