### ISSUE TITLE
[Bug]: RangeFilterState relies on is.integer which can be problematic

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.slice#99]
### What happened?

The `RangeFilterState` [uses `is.integer`](https://github.com/insightsengineering/teal.slice/blob/a449203ab5267fd208fe68d606a89ead1cc9be6a/R/FilterState.R#L1294) to check if the provided value is an integer (vector). However, `is.integer` is typically not what we want. It checks if a number is a 'real' integer. That is, `is.integer(1L)` will return `TRUE` while `is.integer(1)` returns `FALSE`. Since the `checkmate` is already a dependency, we can use `checkmate::check_integerish` which is probably what we want here.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by nikolas-burkoff** [comment]
>  we can use checkmate::check_integerish which is probably what we want here.

I think `test_integerish` is better returning a logical:
![image](https://user-images.githubusercontent.com/15201933/202718881-77193a7b-adab-4a5b-9902-9f0fa0bf5b0e.png)
